@startuml c4-habitree-level1
!include <c4/C4_Context.puml>
!include <C4/C4>  
!include <C4/C4_Container> 

Person(user, "Nutzer", "Möchte seine Habits tracken")
System_Boundary(gewohnheitstier, "Habitree") {
  
  Container(api,    "Backend API", "Node.js/Express.js", "Verarbeitet Anfragen von der Mobile App ")
  
  Container(mobileApp, "Mobile App", "Expo/JavaScript/", "Mobile UI für Nutzerinteraktion")
  ContainerDb(db,    "Database",  "PostgreSQL", "Datenspeicherung")
}




Rel(user, mobileApp, "nutzt")
Rel_R(api,       db,     "SQL-CRUD")
Rel(mobileApp, api, "REST-Calls")


@enduml