@startuml c4-habitree-level2
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Nutzer, "Nutzer")

Container(frontend, "Mobile App", "Expo (React Native)", "Frontend läuft auf dem Handy")
Container(backend, "Backend API", "Node.js, Express", "Backend läuft auf dem externen Hochschulserver")

ContainerDb(db, "PostgreSQL Datenbank", "PostgreSQL", "Speichert Nutzerdaten, Gewohnheiten, etc.")
Container(prisma, "Prisma ORM", "Node.js Modul", "Schnittstelle zwischen Backend und Datenbank")

Nutzer --> frontend : nutzt

frontend -> backend : kommuniziert via REST API 
prisma --> db : SQL-Zugriff auf Datenbank

backend -> prisma : persistiert Daten und greift über ORM auf DB zu



@enduml
