import { StyleSheet, Dimensions } from 'react-native';
const { width: windowWidth, height: windowHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  authContainer: {
    width: '100%',
    padding: 20,
    borderRadius: 12,
    backgroundColor: '#f9f9f9',
    alignItems: 'center',
  },
  authInput: {
    height: 50,
    width: '100%',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    backgroundColor: 'white',
    fontSize: 16,
    marginBottom: 10,
    color: '#333',
  },
  authButton: {
    backgroundColor: 'rgb(25, 145, 137)',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
  authButtonDisabled: {
    backgroundColor: '#9e9e9e',
  },
  authButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  authMessage: {
    color: '#d32f2f',
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 10,
  },
  switchAuthButton: {
    marginTop: 15,
    paddingVertical: 10,
  },
  switchAuthButtonText: {
    color: 'rgb(25, 145, 137)',
    textAlign: 'center',
    fontSize: 14,
  },
  noHabitsText: {
    color: '#888',
    fontStyle: 'italic',
    textAlign: 'center',
    marginVertical: 16,
  },
  container: {
    flex: 1,
    padding: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: '#00000088',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 24,
    borderRadius: 12,
    width: '80%',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    marginBottom: 10,
  },
  predefinedItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
  },
  fab: {
    position: 'absolute',
    bottom: windowHeight * 0.02,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgb(25, 145, 137)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  fabText: {
    color: 'white',
    fontSize: 32,
    fontWeight: '600',
    lineHeight: 40,
  },
  contentContainer: {
    padding: 16,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
  },
  greetingText: {
    fontSize: 28,
  },
  motivationQuote: {
    marginBottom: 20,
    fontSize: 16,
    fontStyle: 'italic',
  },
  sectionTitle: {
    marginBottom: 12,
    fontSize: 22,
    fontWeight: '600',
  },
  habitTitle: {
    marginBottom: 16,
    fontSize: 20,
  },
  chartSelector: {
    marginBottom: 16,
  },
  chartButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#e0e0e0',
  },
  chartButtonSelected: {
    backgroundColor: 'rgb(25, 145, 137)',
  },
  chartButtonText: {
    fontSize: 14,
  },
  chartButtonTextSelected: {
    fontWeight: 'bold',
    color: 'white',
  },
  chartImage: {
    width: '100%',
    height: windowHeight * 0.2,
    marginBottom: 20,
    borderRadius: 12,
  },
  habitListContainer: {
    borderRadius: 12,
    padding: 16,
  },
  habitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: windowHeight * 0.015,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e0e0e0',
  },
  habitTextContainer: {
    marginLeft: 12,
  },
  habitLabel: {
    fontSize: 16,
    fontWeight: '500',
  },
  habitDescription: {
    fontSize: 14,
    opacity: 0.7,
    marginTop: 4,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#A1CEDC',
    borderColor: '#A1CEDC',
  },
  checkmark: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  profileRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    gap: 6,
  },
  profileImageWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 20,
    borderColor: 'transparent',
  },
  profileImageToday: {
    borderColor: 'rgb(25, 145, 137)', // gelber Rahmen für den heutigen Tag
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  streakContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginVertical: 20,
    marginTop: 10,     // optional: etwas nach oben rücken im Layout
  },
  streakBackgroundImage: {
    position: 'absolute',
    width: 85,
    height: 85,
    top: -27,          // Tropfen leicht nach oben verschieben
    opacity: 0.25,
  },
  streakNumber: {
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'rgb(25, 145, 137)',
    lineHeight: 40,
    includeFontPadding: false,
    textAlignVertical: 'center',
    zIndex: 1,
  },
  weekdayRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 24,     // 👈 extra Platz zwischen Tropfen/Zahl und Wochentagen
    gap: 8,
  },
  weekdayCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  weekdayFilled: {
    backgroundColor: 'rgba(25, 145, 137, 0.2)',
    borderColor: 'rgba(25, 145, 137, 0.3)',
  },
  weekdayToday: {
    borderColor: 'rgb(25, 145, 137)',
    borderWidth: 3,
    backgroundColor: 'rgba(25, 145, 137, 0.35)',
  },
  weekdayText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  weekdayTextToday: {
    color: 'rgb(25, 145, 137)',
    fontWeight: '700',
  },
   streakModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '85%',
    alignItems: 'center',
  },
   streakModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
    color: 'rgb(25, 145, 137)',
  },
  streakModalText: {
    fontSize: 15,
    textAlign: 'center',
    color: '#444',
    marginBottom: 16,
  },
  streakModalImage: {
    width: 100,
    height: 100,
    opacity: 0.8,
    marginBottom: 12,
  },
  streakCloseButton: {
    marginTop: 8,
    backgroundColor: 'rgb(25, 145, 137)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
  },
  streakCloseButtonText: {
    color: '#fff',
    fontWeight: '600',
    textAlign: 'center',
  },

});
