= Projektplan: {project-name}
Laurenz Born <laurenz.born@stud.htw-dresden.de>; Alexander Chlebowski <alexander.chlebowski@stud.htw-dresden.de>; Leonhard Hermann <leonhard.hermann@stud.htw-dresden.de>; Johann Schmidt <johann.schmidt@stud.htw-dresden.de>; Kimi Jerke <kimi.jerke@stud.htw-dresden.de>; Jannes Lehmann <s86317@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Kurze Beschreibung und Überblick zum Dokument.


== Projektorganisation

=== Projektteamstruktur
|===
|*Name* |*Rolle*
|Laurenz Born| Developer
|Alexander Chlebowski| Developer
|Leonhard Hermann| Scrum Master
|Johann Schmidt|Developer
|Kimi Jerke|Developer
|Jannes Lehmann| Product Owner
|===
// Personen nach Rollen und alphabetisch ordnen

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

== Praktiken und Bewertung

|===
| *Kategorie* | *Praktik*

| Management
| Nutzung des Scrum-Frameworks zur strukturierten Projektorganisation +
- Arbeit in festen Zyklen (Sprints) von jeweils 4 Wochen +
- Weekly-Meetings (30–45 Minuten) zur Besprechung und Aufzeigung des aktuellen Arbeitsstatus der Mitglieder, Aufgabenverteilung und operativer Planung für die nächste Woche und Identifikation von Hindernissen +
- Aufgaben werden in einem gemeinsamen Miro-Board visualisiert und zusätzlich im Discord-Chat dokumentiert, um Transparenz zu gewährleisten +
- Aufgabenverteilung erfolgt zum großen Teil nach dem Prinzip der Freiwilligkeit zur Förderung eines positiven Arbeitsklimas in einem Team mit flachen Hierarchien

| Planung & Tracking
| Sprint Planning zu Beginn jeder Iteration legt gemeinsam das Sprintziel fest +
- Bearbeitung der vom Professor bereitgestellten Iterationsdokumente +
- Zerlegung, Aufwandsschätzung, Konkretisierung und Priorisierung von User Stories und den Aufgaben in den Iterationsdokumenten. +
- Zerlegung von hochpriorisierten User Stories in kleinere Tasks, vor allem in den späteren Iterationen.  +
- Aufwandsschätzung und Zuweisung der Tasks an Teammitglieder. Task in den früheren Iterationen beziehen sich primär auf die vom Professor bereitgestellten Aufgaben aus den Iterationsdokumenten. Im Verlauf der iterativen und agilen Entwicklung liegt nun aber mehr und mehr der Fokus auch auf den User Storie- Task.  +
- Kontinuierliche Pflege des Product Backlogs (Ergänzung, Priorisierung, Schätzung, Zerlegung) durch Product Owner und Scrum Master in Abstimmung mit dem Entwicklungsteam.

| Retrospektive & Reflexion
| Nach jedem Sprint findet eine Retrospektive statt, in der das Team seine Zusammenarbeit reflektiert. +
- Jeder Mitarbeiter hat 10 min Zeit  positive und negative Eindrücke und Ereignisse, die er während der letzten Iteration erfahren hat, darzulegen.  +
- Gegenseitiger Respekt ist bei uns sehr wichtig, sodass kein Mitglied während seiner Erklärungen durch andere verbessert, berichtigt oder unterbrochen werden darf.  +
- Protokollierung aller technischen, sozialen und organisatorischen Problemen im Team durch den Scrum Master. +
- Konkrete Maßnahmen zur Verbesserung werden abgeleitet und im "Lessons Learned"-Teil der Dokumentation dokumentiert.  +
- Wie alle weiteren Meetings wird auch die Retrospektive im Miro- Board aus Gründen der Transparenz im Team jeden sichtbar gemacht.  +
- Zum Ende der Retrospektive soll jedes Mitglied seine Hapiness bewerten. Hierfür haben wir einen Hapiness- Index eingeführt. Diesen protokollieren wir auch um Entiwcklungen und Trends in den Emotionen einzelner Mitglieder sehen zu können.
|===


=== Definition of Ready
// Definition of Ready 
- Die Defninition of Ready beschreibt, wann ein Backlog Item als “bereit zur Umsetzung” gilt. Dazu müssen folgende Inhalte stimmen:
    - Die Akzeptanzkriterien sind klar formuliert
    - Die Abhängigkeiten zu anderen Issues sind geklärt
    - Story ist klein genug, um in einem Sprint abgeschlossen zu werden
    - Das Team versteht die Issue/Story inhaltlich und technisch
    - Design/Ui liegt vor, falls nötig
    - Testkriterien oder Hinweise sind definiert



=== Definition of Done
- Die Definition of Done legt fest, wann ein Backlog Item als vollständig abgeschlossen gilt. Dazu müssen folgende Inhalte stimmen:
    - Der Code ist implementiert und gebaut
    - Der Code ist reviewed 
    - Es existieren automatisierte Unit Tests
    - Alle Tests sind erfolgreich bestanden.
    - Die Funktion ist in der Testumgebung funktionsfähig
    - Dokumentation wurde aktualisiert
    - Die Akzeptanzkriterien der Story sind vollständig erfüllt 
    - Die Software ist frei von bekannten Fehlern
    - Product Owner hat abgenommen

== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
|===
|*Herausforderung* |*Vorgehensweise*

|**1. iOS-Entwicklung mit Swift und Xcode**  +
Problem: Swift & Xcode funktionieren ausschließlich auf macOS, das Team besitzt mobile iOS- Geräte jedoch kaum Macs
|Versuch über virtuelle macOS Maschine scheiterte bedauerlicherweise.  +
Daher Entscheidung gegen native Entwicklung mit Swift und Xcode. Stattdessn wurde nach plattformübergreifender Lösung gesucht

|**2. Android-Entwicklung schwer testbar**  +
Problem: Kaum Teammitglieder besitzen Android Geräte
|Testen wäre nur über Emulatoren möglich gewesen.  
Für stabiles Testen auf echter Hardware nicht praktisch umsetzbar. Somit wurde Entschluss gefasst auch keine native Android- App zu entwickeln.

|**3. Allgemeines Plattformproblem bei nativer Entwicklung:**  +  
Problem: Doppelte Entwicklungsarbeit für iOS und Android nicht schaffbar in der Zeit und mit unseren begrenzten Ressourcen und Humankapital.
|Ressourcenmangel bei kleinem Team  +
Stattdessen: Fokus auf Cross-Plattform Technologie.

|**4. Auswahl geeigneter Cross-Plattform-Technologie**  +
Problem: Verschiedene Technologien verfügbar, alle jeweils mit eigenen Vor und Nachteilen  +
*a) Flutter:*  +
- nur virtuelle Testumgebung verfügbar  +
- kein Test auf echter Hardware möglich  +
- Hoher Speicherverbrauch, da Flutter eher für größere Projekte vorgesehen ist  +
- Eingeschränkte Nutzung von Drittanbieter Bibliotheken  +
 
*b) Expo/React Native:*  +
- Live Testen möglich  +
- mehr Drittanbieterunterstützung  + 
-bessere Einstiegshürde  +
|Entscheidung fiel auf **Expo mit React Native**, da:  +
- Teammitglieder beötigen nur eine zusätzliche App namens Expo Go auf dem Handy und einen PC mit dem man programmieren kann  +
- Live Testing auf echter Hardware mittels QR-Scan (Expo Go)  + 
- Nutzung vertrauter Webtechnologien (JavaScript, TypeScript)  +
- Schnelles Ausführen, Testen und Debugging  +
- Konfiguration mit JSON als Lokalspeicher +
- Kein Mac erforderlich, Entwicklung auf Windows möglich  +

|===

== Erkenntnisse (Lessons learned)
// Führen Sie hier die wesentlichen Erkenntnisse auf, die Sie in den Retrospektiven gewonnen haben. Legen Sie besonderen Fokus auf die Maßnahmen, die Sie getroffen haben um Verbesserungen in den verschiedenen Aspekten des Projekts zu erzielen, z.B. dem Entwicklungsprozess, der technischen und organisatorischen Umgebung oder der Zusammenarbeit im Team.

|===
|*Ereignis* |*Maßnahme* |*Erkenntnis*
| Ausstieg aus der Gruppe von Frederic Egle (Developer) | - Gruppenberatung in der ersten Retrospektive  +
- Neuverteilung von Frederics Aufgaben auf andere Teammitglieder, besonders bezogen auf das Development- Team  +
- Ist- Stand- Analyse, was Frederic von Frederics bisherigen  Arbeitsstand.  Durch ihn wurde bis zu dem damaligen Zeitpunkt keinerlei Leistung erbracht.
| - Ausstieg eines Gruppenmitgliedes ist nicht unmöglich  +
- Es entsteht massiv Mehrarbeit für die verbleidenden Gruppenmitglieder, insbesonders die Entwickler  +
- Es müssen zeitliche Puffer existieren in der taktischen Planung um den Erfolg des Projektes nicht zu gefährden und um in den angegebenen Zeiträumen alle Aufgaben abarbeiten zu können +
- Strategische Planung im Vorhinein und  Abwägung potenzieller Risiken vor allem bei der Teamstruktur sind unabdingbar. Hierfür eignet sich eine Visualisierung im Git Hub Risk- Board.
- Wöchentliche  Meetings mit kurzer Arbeitsstandangabe und nächster Schritte sind elementar um zu sehen dass jeder Mitarbeiter effizient arbeitet und das Projekt nicht gefährdet wird.
| Terminfindung, vor allem bei außerplanmäßigen Meetings ist schwer | - Termine zeitig und langfristig planen  +
- Erinnerungen nochmals im Vorhinein absetzen (z.B.: über Whats- App)  +
- Nutzen von Abstimmungen oder Ereignis- Objekten  +
- Einführung eines Team- Kalenders, z.B.: im Miro Board
| - Je größer die Gruppe ist, desto langfristiger muss die Planung erfolgen.  +
-  Nicht jeder Beteiligte muss in jedem Meeting zwangsläufig anwesend sein. So reicht es z.B.: wenn das Sprint- Review nur von 3 Personen durchgeführt wird. Hierbei ist wichtig dass die Mitarbeitenden sich abwechseln, damit jeder Mitarbeiter in einem ausgewogenen Maße entlastet werden kann, aber dennoch seine Bedeutung für die Gruppe erkennt. Dies führt dazu, dass alle Akteure sich mit der Gruppe, der Aufgabe und dem Projekt identifizieren können.  +
- Es braucht einen Organisator, der alle Meetings und Treffen sowohl innerhalb der Gruppe, als auch zwischen den Mitarbeitenden und weiteren Stakeholdern plant und organisiert. Dies ist im Scrum- Framework der Scrum Master.  +

| Konflikte innerhalb des Teams hinsichtlich Arbeitsverteilung, Engagement und Verlässlichkeit
| - Regelmäßige kurze Standup- Meetings, wo jeder Mitarbeitende seine Arbeitsstand, Herausforderungen und Probleme der letzten und der kommenden Woche dem Team mitteilt.  +
- Bei Konflikten ist Kommunikation das A und O. Dabei ist es wichtig die Konflikte bereits in Ihrer Entstehung anzusprechen und zu charakterisieren. Sonst stauen diese sich immer weiter auf und werden im schwerer lösbar. Als Negativbeispiel lässt sich hier ebenfalls unser ehemaliger Entwickler Frederic anbringen.   +
|- Jeder Akteur des Teams sollte erkennen, dass er ein wichtiger und unersetzlicher Bestandteil des Teams ist, welchen Vertrauen und Wertschätzung entgegengebracht wird. Dies schafft ein Zusammenheitsgefühl, gegenseitigen Respekt, Unterstützung und Motivationssteigerung.  +
- Bewältigungen von Konflikten haben auch positive Auswirkungen, da dadurch der Gruppenzusammenhalt wächst und neue Strategien entwickelt werden können. Somit können Konflikte auch indirekt die Gruppe voran bringen.
| Mitteilungen über unbeachteten Kommunikationskanal, was dazu führte, dass der Empfänger die Nachrichten nicht gelesen hatte und dadurch wichtige Sachen im Sprint- Review nicht dargestellt werden konnten
|- Vereinbarung von gemeinsamen Kommunikationskanälen, die allen Teammitgliedern bekannt sind, und von jedem regelmäßig genutzt werden und genutzt werden können. (z.B.: keine Plattformabhängigkeit)  +
- Festlegung von wenigen, bestenfalls einen bis zwei festen Kommunikationswegen. In unserem Team nutzen wir WhatsApp für den täglichen Nachrichtenaustausch und Discord für den Transfer umfangreicher Dokumente und Online- Meetings.  +
| - Vorab- Festelegung der genutzten Kommunikationsplattformen und dessen zeitlicher Nutzung.  
| Unkenntniss über Reihenfolge des Arbeitens gemäß des Scrum- Frameworks und den Prinzipien der iterativen und agilen Entwicklung
| -  
|
|===