= Projektplan: {project-name}
Laurenz Born <laurenz.born@stud.htw-dresden.de>; Alexander Chlebowski <alexander.chlebowski@stud.htw-dresden.de>; Leonhard Hermann <leonhard.hermann@stud.htw-dresden.de>; Johann Schmidt <johann.schmidt@stud.htw-dresden.de>; Kimi Jerke <kimi.jerke@stud.htw-dresden.de>; Jannes Lehmann <s86317@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Kurze Beschreibung und Überblick zum Dokument.


== Projektorganisation
=== Projektteamstruktur
|===
|*Name* |*Rolle*
|Laurenz Born| Developer
|Alexander Chlebowski| Developer
|Leonhard Hermann| Scrum Master
|Johann Schmidt|Developer
|Kimi Jerke|Developer
|Jannes Lehmann| Product Owner
|===
// Personen nach Rollen und alphabetisch ordnen

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

|===
|*Kategorie* |*Praktik*
| Management | Iterative Entwicklung unter Nutzung des Scrum- Frameworks  +
- Arbeit in festen Zyklen (Sprints), von jeweils 4 Wochen  +
- Nach jeden Sprint erfolgt Retrospektive, in der Team seine Arbeitsweise rekapituliert und überdenkt  +
- Jeder Sprint wird im Vorhinein durch ein längeres "Sprint- Planning" Meeting taktisch geplant  +
- Jede Woche erfolge kurze  
|===


=== Definition of Ready
// Definition of Ready 
- Die Defninition of Ready beschreibt, wann ein Backlog Item als “bereit zur Umsetzung” gilt. Dazu müssen folgende Inhalte stimmen:
    - Die Akzeptanzkriterien sind klar formuliert
    - Die Abhängigkeiten zu anderen Issues sind geklärt
    - Story ist klein genug, um in einem Sprint abgeschlossen zu werden
    - Das Team versteht die Issue/Story inhaltlich und technisch
    - Design/Ui liegt vor, falls nötig
    - Testkriterien oder Hinweise sind definiert



=== Definition of Done
- Die Definition of Done legt fest, wann ein Backlog Item als vollständig abgeschlossen gilt. Dazu müssen folgende Inhalte stimmen:
    - Der Code ist implementiert und gebaut
    - Der Code ist reviewed 
    - Es existieren automatisierte Unit Tests
    - Alle Tests sind erfolgreich bestanden.
    - Die Funktion ist in der Testumgebung funktionsfähig
    - Dokumentation wurde aktualisiert
    - Die Akzeptanzkriterien der Story sind vollständig erfüllt 
    - Die Software ist frei von bekannten Fehlern
    - Product Owner hat abgenommen

== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
// Führen Sie hier die wesentlichen Erkenntnisse auf, die Sie in den Retrospektiven gewonnen haben. Legen Sie besonderen Fokus auf die Maßnahmen, die Sie getroffen haben um Verbesserungen in den verschiedenen Aspekten des Projekts zu erzielen, z.B. dem Entwicklungsprozess, der technischen und organisatorischen Umgebung oder der Zusammenarbeit im Team.

|===
|*Ereignis* |*Maßnahme* |*Erkenntnis*
| Ausstieg aus der Gruppe von Frederic Egle (Developer) | - Gruppenberatung in der ersten Retrospektive  +
- Neuverteilung von Frederics Aufgaben auf andere Teammitglieder, besonders bezogen auf das Development- Team  +
- Ist- Stand- Analyse, was Frederic von Frederics bisherigen  Arbeitsstand.  Durch ihn wurde bis zu dem damaligen Zeitpunkt keinerlei Leistung erbracht.
| - Ausstieg eines Gruppenmitgliedes ist nicht unmöglich  +
- Es entsteht massiv Mehrarbeit für die verbleidenden Gruppenmitglieder, insbesonders die Entwickler  +
- Es müssen zeitliche Puffer existieren in der taktischen Planung um den Erfolg des Projektes nicht zu gefährden und um in den angegebenen Zeiträumen alle Aufgaben abarbeiten zu können +
- Strategische Planung im Vorhinein und  Abwägung potenzieller Risiken vor allem bei der Teamstruktur sind unabdingbar. Hierfür eignet sich eine Visualisierung im Git Hub Risk- Board.
- Wöchentliche  Meetings mit kurzer Arbeitsstandangabe und nächster Schritte sind elementar um zu sehen dass jeder Mitarbeiter effizient arbeitet und das Projekt nicht gefährdet wird.
| Terminfindung, vor allem bei außerplanmäßigen Meetings ist schwer | - Termine zeitig und langfristig planen  +
- Erinnerungen nochmals im Vorhinein absetzen (z.B.: über Whats- App)  +
- Nutzen von Abstimmungen oder Ereignis- Objekten  +
- Einführung eines Team- Kalenders, z.B.: im Miro Board
| - Je größer die Gruppe ist, desto langfristiger muss die Planung erfolgen.  +
-  Nicht jeder Beteiligte muss in jedem Meeting zwangsläufig anwesend sein. So reicht es z.B.: wenn das Sprint- Review nur von 3 Personen durchgeführt wird. Hierbei ist wichtig dass die Mitarbeitenden sich abwechseln, damit jeder Mitarbeiter in einem ausgewogenen Maße entlastet werden kann, aber dennoch seine Bedeutung für die Gruppe erkennt. Dies führt dazu, dass alle Akteure sich mit der Gruppe, der Aufgabe und dem Projekt identifizieren können.  +
- Es braucht einen Organisator, der alle Meetings und Treffen sowohl innerhalb der Gruppe, als auch zwischen den Mitarbeitenden und weiteren Stakeholdern plant und organisiert. Dies ist im Scrum- Framework der Scrum Master.  +

| Konflikte innerhalb des Teams hinsichtlich Arbeitsverteilung, Engagement und Verlässlichkeit
| - Regelmäßige kurze Standup- Meetings, wo jeder Mitarbeitende seine Arbeitsstand, Herausforderungen und Probleme der letzten und der kommenden Woche dem Team mitteilt.  +
- Bei Konflikten ist Kommunikation das A und O. Dabei ist es wichtig die Konflikte bereits in Ihrer Entstehung anzusprechen und zu charakterisieren. Sonst stauen diese sich immer weiter auf und werden im schwerer lösbar. Als Negativbeispiel lässt sich hier ebenfalls unser ehemaliger Entwickler Frederic anbringen.   +
|- Jeder Akteur des Teams sollte erkennen, dass er ein wichtiger und unersetzlicher Bestandteil des Teams ist, welchen Vertrauen und Wertschätzung entgegengebracht wird. Dies schafft ein Zusammenheitsgefühl, gegenseitigen Respekt, Unterstützung und Motivationssteigerung.  +
- Bewältigungen von Konflikten haben auch positive Auswirkungen, da dadurch der Gruppenzusammenhalt wächst und neue Strategien entwickelt werden können. Somit können Konflikte auch indirekt die Gruppe voran bringen.
|===