= Reflexion Software Engineering 2 – Team 3A (Habitree)
:author: Team 3A – Habitree
:revnumber: 1.0
:revdate: {docdate}
:toc: left
:sectnums:



Dieses Dokument reflektiert die Team- und Prozessarbeit des Projekts *Habitree* im Rahmen des Moduls *Software Engineering 2*.  
Der Fokus liegt gemäß den Vorgaben auf:

* der Zusammenarbeit im Team,
* der Anwendung von Scrum-Praktiken,
* dem Umgang mit Projektmanagement-Werkzeugen,
* den wichtigsten Erfolgen und Misserfolgen,
* sowie den erarbeiteten Lessons Learned.

Technische Details stehen bewusst nicht im Mittelpunkt. Erfahrungen aus *Software Engineering 1* werden an relevanten Stellen als Grundlage einbezogen, die Reflexion bezieht sich jedoch überwiegend auf SE2.

== Einleitung
Im Rahmen des Modules Software Engineering 2 reflektiert Team 3A den Verlauf der gemeinsamen Projektarbeit an der Habit- Tracking App ‚Habitree‘. Der Fokus dieser Reflexion liegt hierbei bewusst auf der Zusammenarbeit im Team, der Organisation des Projektes und der Anwendung agiler Vorgehensweisen und Praktiken entlang des Softwareentwicklungsprozesses. Aufbauend auf unseren Teaminternen Erfahrungen, Learnings und Expertisen aus dem Modul Software Engineering 1, wurden Arbeitsweisen, Rollenverständnis und eingesetzte Werkzeuge kritisch hinterfragt, angepasst und optimiert. Die folgenden Ausführungen basieren auf Retrospektiven, Sprint Reviews und weiterer Kommunikation innerhalb des Teams und sollen zentrale Probleme, deren abgeleiteten Erkenntnisse sowie große Erfolge mit deren jeweiligen Erfolgsfaktoren nachvollziehbar darstellen.
Im Projektverlauf konnten mehrere Maßnahmen identifiziert werden, die sich messbar positiv auf den Teamerfolg ausgewirkt haben.

== Erfolge
=== Erfolg 1 - Simplifizierung Arbeitsprozesse und der Arbeit mit dem Github-Project
Unter anderem kam es zu einer Professionalisierung, Standardisierung und vorallem Vereinfachung des Projekt Management durch Umstellung  von vielen verschiedenen Projektmanagementwerkzeugen auf hauptsächlich GitHub.
Aufgrund einer für unseren Anspruch unzureichenden Note in Software Engineering 1 entschied sich der Scrum Master über die Ferien das Projektmanagement anzupassen um dessen Leistung zu steigern.
Dies endete allerdings in einem überladenen Tool- Mix, in welchen eine in der Cloud befindliche Power Point- im Vorfeld von Meetings erstellt wurde und Überblick über die aktuellen Themen, nächsten Schritte, Probleme und Verantwortlichkeiten geben sollte. 
Zudem wurde das GitHub Board auch genutzt um aktuelle Task den entsprechenden Mitgliedern zuzuweisen. Hinzukommend nutzte das Team auch teilweise das Miro- Board und Discord sowie WhatsApp für  Meetings und Asynchrone Kommunikation. Der grundlegend gute Gedanke neue Technologien und Werkzeuge zu nutzen um die Zusammenarbeit zu verbessern, führte jedoch zu einer Überfrachtung und Verkomplizierung der Projektmanagement- Abläufe.
Ergebnis war immense Mehrarbeit und entsprechend zusätzlicher Zeitaufwand, da verschiedene Projektmanagement- Werkzeuge genutzt, gepflegt und geupdatet werden mussten. Es ergaben sich Inkonsistenzen zwischen den einzelnen Tools und Daten wurden redundant mehrmals niedergeschrieben. Die Mitglieder waren somit verwirrt und wussten nicht, welches Tool gerade die aktuellste Version beinhaltet.
Schon in Software Engineering 1 pflegten wir zudem nicht konsistent unser Git Hub Board und die darin enthaltenen Daten, sodass es auch innerhalb GitHub viele verschiedene und redundante Views, Labels und Task- Formate gab. Meist lag die Idee noch im ausprobieren und drauf loslegen, ohne sich vorher auf einheitliche Strukturen und Vorgehensweisen zu einigen.
Diese Inkonsistenz und unklaren Strukturen führte zu Planlosigkeit hinsichtlich der Abläufe und Umsetzungen im Projekt was Ineffizienz, Missverständnisse und Frustration innerhalb des Teams befeuerte.
Beispielsweise führten diese Arbeitsweisen dazu, dass entsprechend Tasks im Meeting per PowerPoint vergeben wurden aber nicht auf Github erstellt oder dem Team-Mitglied zugeordnet wurden. Teammitglieder mussten somit in PowerPoint sowie im Github-Project nach deren Aufgaben suchen was zum vergessen dieser führte. Zu viele (redundante) Labels resultierten in zu vielen Views und erschwerten die Übersichtlichkeit.
Um neue, präzisere und effizientere Strukturen zu erschaffen, beschlossen wir uns also in einem längeren Meeting, bestehende Inkonsistenzen zu bereinigen. Unsere Maßnahmen im Github waren zum einen die Reduktion der überflüssigen Views und Labels, die Einführung neuer und klarer Sichten in unserem Project- Board sowie die Vereinheitlichung von User Story und Task Formaten, wie auch die Ergänzung von Akzeptanzkriterien zu den entsprechenden Task. Ziel ist es, klare Strukturen zu schaffen welche verständliche Arbeitsabläufe ermöglichen und somit ein zielführendes Arbeiten im Team zu ermöglichen.
So wurden wichtige Sichten wie  ‚Sprint- Backlog -> Tasks from Userstories‘ oder ein ‚Product Backlog -> Userstories‘ angepast und vereinfacht um ein schnelles und übersichtliches Arbeiten mit diesen zu ermöglichen und somit besser nach gängigen Scrum- Methoden zu agieren. Die verbesserte Übersichtlichkeit und Verständlichkeit schaffte ein einheitliches Methodenverständnis unter allen Akteuren des Teams. Überflüssige Tools bzw. Medien wie PowerPoint wurden abgeschafft. Neben der nun minimierten Doppelpflege, Medienbrüchen und Verwirrung innerhalb des Teams, resultierte diese Maßnahme auch in einer transparenteren Arbeitsteilung und einen klaren Zuordnung von Task. Anders als in einer Power Point Tabelle, werden auf Git Hub die einzelnen Mitglieder explizit benachrichtigt, wenn Sie einem bestimmten Task zugeordnet wurden. Dies verhindert, dass Aufgaben übersehen oder vergessen werden. Die alleinige Nutzung von Github zur Zuordnung von Aufgaben ermöglicht einen Zentralen Ort, an dem alle Teammitglieder deren Aufgaben einsehen und bearbeiten können.  
Durch die Einführung von klareren und feingranulareren Labels, aber gleichzeitig der Minimierung der Labelanzahl auf das nötigste, weiß jedes Mitglied auch was für eine Art Task er genau abarbeiten muss. Hierfür nahmen wir eine Untergliederung in Story-, Documentation- und Implementation- Task vor. Während Story Task abgeleitete Programmierungs- bzw Implementations-Aufgaben im Code zur Erfüllung von den User Stories darstellen, adressieren Documentation Task konkrete Dinge die in die einzelnen Dokumenten niedergeschrieben werden müssen und Implementation Task dienen zur Bearbeitung allgemeiner Technischer Probleme und Aufgabenstellungen welche nicht direkt aus einer User Story abgeleitet wurden bzw. werden können. Wenn ein Mitglied nun einen Task assigned wird, weiß es somit intuitiv auf welche Problemdimension der jeweilige Task referenziert.  

=== Erfolg 2 - Einführung strukturierter Scrum- Meetings & KPI’s
Neben dem effizienteren Projektmanagement wurde auch die Scrum- Arbeitsweise nochmals überarbeitet und optimiert. Unter anderem wurde eine feste Meeting- Struktur eingeführt bzw. umgestaltet mit Weekly- Meetings welche in Ihrer Dauer auf 30- 60 min/Woche eingeschränkt wurden. Zudem wurden auch zu Beginn eines jeden Sprints ein ‚Sprint- Planning‘- Meeting eingeführt, in welchem vom Product Owner im Vorfeld priorisierte User Stories, die in den Sprint aufgenommen werden sollen vom Rest des Teams gewichtet werden und anschließend Task abgeleitet werden. Hierbei validiert ins besonders das Entwicklerteam die technische Umsetzung und Machbarkeit der einzelnen Stories. Dies stellt eine Orientierung an bestehenden Scrum- Prinzipien dar und ermöglicht eine effizientere Arbeitsweise innerhalb des Teams.
Zudem wurden Key Performance Indikatoren (KPI’s) eingeführt, welche kontinuierlich den Projekterfolg messen sollen. Als messbare Kennzahlen hierfür wurden vom Scrum Master ein ‚Hapiness Index‘, eine  ‚Task- Sucess- Rate‘ und eine ‚Capacity- Board‘ eingeführt. Der Hapiness- Score soll einen Überblick über die Zufriedenheit geben der einzelnen Teammitglieder. In jeder Retrospektive wird vom Scrum Master abgefragt, wie zufrieden die einzelnen Teammitglieder sind, im Hinblick auf das Projekt, dessen Fortschritt und die Zusammenarbeit innerhalb des Teams. Die Zufriedenheit soll hierbei quantifiziert werden was bedeutet, dass jedes Mitglied seine emotionale Stimmung anhand einer Skala von 1- 10 bewerten soll, wobei 10 die höchstmögliche emotionale Grundstimmung darstellt und 1 den worst- case abdeckt. In unserem Kapazitäten- Board, welches initial auf der Power Point gepflegt, dann jedoch auf Git Hub transferiert wurde, wird der Einsatz von den einzelnen Teammitgliedern für das Projekt je Woche gepflegt. In jeden Weekly wird somit vom Scrum Master erfasst wie viele Wochenstunden in der kommenden Woche, die einzelnen Akteure einsetzbar sind. Hierbei kann man sich entscheiden zwischen den Größen: Kein Einsatz, 1-2 h/Woche, 2-3h/Woche, 5-7h/Woche oder mehr als 7h/Woche entscheiden. Um ein Betrügen zu verhindern, wird im Nachgang jeweils überprüft, dass die erbrachte Arbeitsleistung der angegebenen Arbeitszeit in etwa entspricht und dass nicht konstant ein Akteur weniger arbeitet als andere. Für besonders motivierte Mitglieder, die mehr als 5 mal über 7 Stunden arbeiteten soll zu Ende des Projektes eine Belohnung in Form eines spendierten Essens erfolgen. Die Task- Fortschrittsrate gibt Überblick über die absolvierten Task pro Woche bzw. Sprint an. Sie zeigt klare Tendenzen hinsichtlich Effizienz und Organisation innerhalb des Teams an und lässt sich bei Bedarf auch auf einzelne Mitglieder runterbrechen.  Wichtig zu erwähne ist, dass die angeführten KPI’s keine direkte Kontrolle der Mitarbeiter beinhalten sollten, sondern lediglich den Scrum Master grobe Tendenzen innerhalb Arbeitsweise, Projektfortschritts und Betriebsklima geben sollen. Durch die Metriken sind unter anderem Überlastung und Demotivation der Arbeiter ersichtlich und eine bewusste Anpassung von Sprintumfängen und Aufgabenverteilung sowie besser Diskussionen in der Retrospektive möglich, da sich nun einzelne Gefühle quantifizieren lassen. 

=== Erfolg 3 - Starker Teamzusammenhalt und klare Rollenverteilung
Als einen weiteren positiven Punkt lässt sich der grundsätzlich starke Teamzusammenhalt und die klare Rollenverteilung anbringen. Prinzipiell wurde innerhalb der Module SE1 und SE2 ein wertschätzendes Team mit klaren Regeln, Visionen und bis auf eine Ausnahme  funktionierender Zusammenarbeit gebildet. Zudem wurde zu Beginn des Software Engineering 2 Modules auch erfolgreich ein neues und zugelostes Teammitglied integriert in die bestehenden Strukturen. Unsere Rollen sind klar verteilt und wurden in SE2 geschärft. So haben wir zu einem den Product Owner, welcher das Domänenwissen über Habits hat, sowie einen konkreten Überblick über Vision, User Stories und Features hat. Er priorisiert User Stories, welche anschließend in dem Sprint Planning- Meeting vor allem mit dem Entwickler- Team gewichtet und geschätzt werden hinsichtlich Komplexität und Aufwand. Der Scrum Master ist für die Organisation und Abwicklung aller Meetings vorhanden, sofern es keine spezialisierten Dev.- Team Meetings sind. Zudem ist er die unterstützende Instanz bei Konflikten und Problemen. Weitere Aufgaben von Ihm ist das grobe Projektcontrolling, auch hinsichtlich eingesetzter Techniken, also ob die Ist- Techniken mit den aus der Vorlesung und Praktikum gegebenen Soll- Techniken übereinstimmen. Zudem unterstützt er den auch den Product Owner. Das Dev.- Team ist für die konkrete Implementierung und Validierung von ‚Habitree‘ zuständig, wobei sich auch innerhalb dieses Teams spezifische Zuständigkeitsbereiche ergeben. So gibt es zum Beispiel Verantwortliche für das Backend, Frontend und das Testen. Ein Problem, was sich dabei ergibt sind Wissensinseln, die aber durch wöchentliche Meetings und einem Austausch innerhalb des gesamten Entwicklerteams ausgeglichen werden sollen. Die jetzige Beständigkeit unserer Teamstruktur baut auf verschiedenen Problemen auf, die in der Vergangenheit erfolgreich gemanagt wurden. Unter anderem bewältigten wir den Austritt eines Teammitgliedes noch in SE1,sowie  das ein Teammitglied nicht konstant arbeitet oder auch Kommunikationsprobleme durch verschiedene synchrone und asynchrone Kommunikationswege. Diese Hürden führten dazu, dass jeder seine Rolle und seinen Beitrag für das Team kennt. Alles in allem haben wir fast immer eine hohe Teilnehmerquote in Meetings und ein wertschätzendes Klima aufgebaut mit relativ flachen Hierarchien.


Die beschriebenen Erfolge zeigen, dass es dem Team im Verlauf von Software Engineering 2 gelungen ist Strukturen, Prozesse und Zusammenarbeit deutlich zu professionalisieren. Gleichzeitig legte aber auch gerade diese zunehmende Strukturierung und Optimierung Schwachstellen offen, die zuvor entweder verdeckt waren oder aufgrund geringer Komplexität keine wesentliche Rollen spielten.



== Misserfolge

Die beschriebenen Erfolge zeigen, dass es dem Team im Verlauf von Software Engineering 2 gelungen ist Strukturen, Prozesse und Zusammenarbeit deutlich zu professionalisieren. Gleichzeitig legte aber auch gerade diese zunehmende Strukturierung und Optimierung Schwachstellen offen, die zuvor entweder verdeckt waren oder aufgrund geringer Komplexität keine wesentliche Rollen spielten.
Im Folgenden werden daher drei zentrale Misserfolge bzw. Probleme beschrieben, die den Verlauf des Software Engineering- Projektes negativ beeinflussten, aus denen jedoch konkrete Maßnahmen und langfristige Erkenntnisse abgeleitet wurden.

=== Misserfolg 1 - Sprint Management und Planungsprobleme durch unregelmäßige und schwankende Kapazitäten der einzelnen Teammitglieder
Der erste Misserfolg bezieht sich auf unser Sprint- Management bedingt durch Planungsprobleme aufgrund schwankender Kapazitäten der einzelnen Mitglieder.  Unser Sprintmanagement stand im gesamten Modul vor wiederkehrenden Herausforderungen, die primär aus der studentischen Situation resultierten.  
So wurde unser Projekt nicht in Vollzeit durchgeführt, sondern es entstand parallel zu mehreren anderen Modulen, Deadlines, Praktika oder anderen Projekten.  Somit variierten die Kapazitäten der einzelnen Mitarbeiter zwischen und innerhalb der einzelnen Wochen erheblich.  Zu Beginn jedes Sprints priorisierten wir im Sprint Planning - Meeting User Stories, zerlegten diese in konkrete Aufgaben und nahmen sie in das Sprint Backlog auf. Zudem fragte der Scrum Master jede Woche, auch im Zuge der KPI- Auswertung, die Einsatzfähigkeit in Stunden der Mitglieder ab (z.B.: innerhalb des Kapazitätsboards in Git Hub). Trotz dieser Workflows zeigten sich jedoch Probleme innerhalb der eigentlichen Umsetzung.  So konnten wir in einigen Iterationen deutlich mehr leisten als geplant, sodass der Sprint nach zwei Wochen schon vollständig abgeschlossen war. In anderen Sprints hatten wir teilweise weniger Zeit als erwartet, sodass nicht alle geplanten Task abgearbeitet werden konnten.  Dies führte zu einer Divergenz vom theoretischen Scrum- Timeboxing und der Anwendung der Scrum- Praktiken in dem studentischen Alltag. 
Dies führte dazu, dass wir das Sprint- Framework leicht abändern mussten um auf die sich schnell ändernde  studentische Umwelt angepasst zu sein. Wenn ein Sprint deutlich vorzeitig abgeschlossen wurde mit all seinen Aufgaben (als Zeitpunkt setzten wir 10 Tage vor dem eigentlichen Ende an), führten wir ein Refill- Meeting ein, um neue Stories aus dem Product Backlog aufzunehmen.  Wie im eigentlichen Sprint Planning- Meeting wurden die entsprechenden Product Backlog Items erst vom Product Owner priorisiert, dann innerhalb des Teams geschätzt hinsichtlich Komplexität und Aufwand und anschließend wurden konkrete Task abgeleitet. 
Das Ziel sollte die Vermeidung unnötiger Leerlaufzeit und die kontinuierliche Steigerung des Geschäftswertes sein. 
Wurden Aufgaben bis Sprint Ende nicht abgeschlossen, dann mussten diese aus dem alten Sprint entfernt werden, erneut refined und für den nächsten Sprint eingeplant werden.  
Die bewusste Abweichungen von den in der Vorlesung geschilderten Scrum- Prinzipien barg auch einige Nachteile. So verschwommen teilweise die Sprintgrenzen, was die Transparenz, vor allem auch gegenüber Stakeholdern in Sprint Reviews negativ beeinflusste. Auch die Planbarkeit und strategische Steuerung des Projektes wurde komplexer.  
Wir haben gelernt, dass Sprints im universitären Umfeld anders funktionieren als in Vollzeit- Produktteams. Während in Scrum  formell davon ausgegangen wird, dass Teams eine annährend konstante Velocity besitzen, sind studentische Teams eher volatil und somit tendenziell schlechter planbar. In der beruflichen Praxis ist es selten der Fall, dass z.B.: Mitarbeiter nur für 3 bis 10 Stunden die Woche auf einem Projekt eingesetzt sind. Unser adaptives Vorgehen weicht zwar von einigen gängigen Scrum- Best- Pratices ab (u.a. dass Sprints nicht nachgefüllt werden sollten mit weiteren PBI’s), ergab jedoch aus Projektsicht einen sinnvollen Kompromiss. 
In zukünftigen Projekten würden wir Sprints bewusst kürzer halten (wie auch schon zu Ende gemacht, da unser Sprint 3 nur für eine Dauer von 14 Tagen angedacht war) , da sich auf kürzere Zeit kapazitive Schwankungen tendenziell geringer ausfallen. Zudem würden wir dieses Thema auch schon frühzeitig in unser Risikoboard aufnehmen.  Pufferzeiten in Sprints, würden wir vor allem mit der Beseitigung von Bugs, Dokumentations- Aufgaben und Verbesserung unserer Architektur und unseres Codes verbringen. 

=== Misserfolg 2 - Entstehung von Inselwissen, aufgrund fehlendes horizontalen Wissenstransfers
Ein weiterer Misserfolg besteht in der Entstehung von Inselkompetenzen und einen fehlenden horizontalen Wissenstransfer. Mit Fortschreiten des Projektes fand eine zunehmende Spezialisierung des Teams in klar voneinander abgegrenzte Domänen statt, gemäß Ihrer Rollen und Verantwortlichkeiten. Dies ist grundsätzlich sinnvoll, gerade bei kleineren Teamgrößen, führt jedoch zwangsläufig zu einer Entstehung von Wissensinseln.  Während der Scrum- Master primär für Meeting Planung, Prozessüberwachung und die Sicherstellung der agilen Arbeitsweise verantwortlich war, kümmerte sich der Product Owner um das Stakeholdermanagement sowie die Priorisierung von User Stories. Das Entwicklerteam untergliederte sich in weitere Subdomänen, so gab es jeweils verantwortliche für das Frontend, Backend und die Testgestaltung. Durch diese Spezialisierung kam es dazu, dass die Teammitglieder über die Sprints hinweg sich immer tiefer in Ihre jeweiligen Subdomänen einarbeiteten ohne das eine ganzheitlicher horizontaler Wissenstransfer entstand. Somit blieben teilweise elementare Dinge wie Architekturentscheidungen bei einzelnen Verantwortlichkeiten hängen. Fielen diese Stress oder Krankheitsbedingt aus, konnten diese Task entweder gar nicht oder maximal unzureichend von anderen Teammitglieder kompensiert werden. Als unser Architekturverantwortliche über Zwei Wochen krankheitsbedingt ausfiel, konnte niemand an der Architektur mit zufriedenstellender Qualität weiter arbeiten. Das Team war dadurch nur eingeschränkt in der Lage flexibel auf zeitkritische Risiken zu reagieren, welche einen Ausfall einzelner Mitglieder adressierten. Wenn dennoch eine Einarbeitung in fremde Themengebiete erfolgte, bestand ein hoher Einarbeitungsaufwand, da die Interaktion zwischen den einzelnen Teammitgliedern nur an Schnittstellen statt fand. 
Zukünftig könnte man Pair Programming einführen, um Wissen direkt zwischen den Rollen auszutauschen. Zudem muss ein noch stärkerer Fokus auf eine saubere, konsistente und nicht zu überladene Dokumentation gelegt werden, sodass man sich Rollenwissen direkt anlesen kann. Zudem könnte man auch Backup- Rollen definieren, sodass jeder Zuständigkeitsbereich von mindestens zwei Gruppenmitglieder prinzipiell erledigt werden kann. 
Wir erkannten, dass technische Spezialisierung zwar effizient erscheint, jedoch langfristig zu strukturellen Risiken führen kann. Um eine nachhaltige Arbeitsweise im Team hervorbringen zu können, muss Wissen aktiv geteilt und ausgetauscht werden, statt sich nur in seine Domäne einzuarbeiten. Software Engineering ist Teamarbeit und bedarf neben technischen auch eine Vielzahl sozialer Kompetenzen.

=== Misserfolg 3 - Scheitern selbstorganisierter Zusammenarbeit bei geringer individueller Motivation eines Teammitgliedes
Unser letzter Misserfolg bezieht sich auf anhaltenden Schwierigkeiten mit einem Teammitglied, deren Ursprung bereits in Software-Engineering 1 lag und sich über den gesamten Zeitraum von Software- Engineering 2 fortsetzte. Trotz der grundsätzlich positiven Dynamik im Team stellte dieser Mitarbeiter die Grenzen flacher Hierarchien und selbstogranisierter, demokratischer Arbeitsweisen wiederholt auf die Probe. 
Dies zeigte sich vor allem in Form von dauerhaft niedriger Motivation, passiven und respektlosen Umgang in Meetings und nicht verkündeten Abwesenheiten. 
Zugewiesene oder vereinbarte Aufgaben wie z.B.: die Erstellung von Wireframes oder Sequenzdiagramme und die Anfertigung eines Benutzerhandbuches wurden teilweise gar nicht, und wenn nur oberflächlich oder mit KI- generierten Inhalten eingereicht. Da dieses Verhalten in keiner Weise unseren internen Qualitätsanforderungen entspricht, entstand ein aktiver Schaden in unserer Arbeitskultur, da teilweise minderwertige Arbeit weiterverarbeitet oder von anderen Mitarbeitern zeitaufwendig verbessert werden musste. 
Zu Beginn des Projektes ging das Team davon aus, dass Freiwilligkeit und ein Partizipativer Führungsstil ausreichen würden um das Engagement sicherzustellen. 
Diese Annahme bewährte sich für die Mehrheit des Teams, jedoch nicht für dieses spezifische Mitglied. Trotz zahlreicher Versuche, intrinsische Motivation zu fördern (z. B.: Unterstützung, flexible Aufgabenauswahl oder nettes verweisen auf unerledigte Task), kam es zu keiner Verbesserung. Die Arbeitsweise dieses Mitglieds blieb bis zum Ende des Projektes auf ein absolutes Minimum beschränkt. Erst durch einen deutlichen Führungswechsel, der von gängigen Methoden der agilen und iterativen Entwicklung abweicht, gelang es uns ein Mindestmaß an Qualität und Pünktlichkeit in seine Arbeit zu bekommen. Angelehnt an das Reifegradmodell von Hersey und Blanchard versuchten wir nur bei dem Mitglied eine erhöhte Aufgabenorientierung vorzunehmen und verbindliche Strukturen zu definieren. Diese beinhalteten eine klare Aufgabenverteilung, verbindliche Deadlines  sowie eine Androhung der Eskalation an Professor oder Coach, wenn sich das Verhalten auch langfristig nicht bessert. Diese Maßnahmen führten kurzfristig zu einer minimalen Verbesserung der Arbeitsergebnisse, änderten jedoch nichts an der Grundeinstellung der Person. Aufgaben wurden nach wie vor nur kurz vor knapp abgegeben, und größtenteils mit KI bearbeitet und auch die Beteiligung in Meetings fand nur sehr sporadisch statt. 
Diese Erfahrungen zeigten uns deutlich, dass Selbstorganisation nicht als Führungsprinzip für alle Teammitglieder geeignet ist, vor allem nicht über einen längeren Zeitraum. Während die meisten Mitarbeiter unter normalen Bedingungen klare Rollen, Freiheiten oder auch flache Hierarchien bevorzugten, stieg mit zunehmenden Projektstress auch die Wünsche nach stärkerer Führung. Vor allem zum Ende hin forderten einige Teammitglieder selber explizite Zuweisung von Task und klare Definitionen der einzelnen Aufgaben mit Deadlines. Dies deckt sich mit den Erkenntnissen des Krisenmanagements, dass in Phasen von hoher Unsicherheit und Druck der Wunsch nach Ordnung und Struktur steigt. 
Trotz des Wandels unseres Führungsstiles, versuchten wir auch zu Ende hin maximale Partizipation aller Mitglieder zu ermöglichen, durch regelmäßige Meetings und wenig Zwang bei der Aufgabenvergabe. Dennoch blieb die Mitarbeit des betroffenen Teammitgliedes bis zum Schluss hin unzuverlässig.  
Zukünftig müsste man schon direkt, wenn sich ein solches Problem abzeichnet mit dem entsprechenden Mitglied kommunizieren und genaue Gründe für seine Demotivation ermitteln. Zudem sollte man einen klar strukturierten Eskalationsprozess erbauen und keine Scheu besitzen diesen umzusetzen.  Teammitglieder mit einen geringeren Reifegrad sei es aus geringer Motivation oder fehlender Kompetenz müssen schon zu Beginn an stark in das Team eingebettet werden und benötigen eine klare Erwartungsklärung zu Ihren entsprechenden Rollen und Zuständigkeiten. 
