= Reflexion Software Engineering 2 – Team 3A (Habitree)
:author: Team 3A – Habitree
:revnumber: 1.0
:revdate: {docdate}
:toc: left
:sectnums:



Dieses Dokument reflektiert die Team- und Prozessarbeit des Projekts *Habitree* im Rahmen des Moduls *Software Engineering 2*.  
Der Fokus liegt gemäß den Vorgaben auf:

* der Zusammenarbeit im Team,
* der Anwendung von Scrum-Praktiken,
* dem Umgang mit Projektmanagement-Werkzeugen,
* den wichtigsten Erfolgen und Misserfolgen,
* sowie den erarbeiteten Lessons Learned.

Technische Details stehen bewusst nicht im Mittelpunkt. Erfahrungen aus *Software Engineering 1* werden an relevanten Stellen als Grundlage einbezogen, die Reflexion bezieht sich jedoch überwiegend auf SE2.

== Einleitung
Im Rahmen des Modules Software Engineering 2 reflektiert Team 3A den Verlauf der gemeinsamen Projektarbeit an der Habit- Tracking App ‚Habitree‘. Der Fokus dieser Reflexion liegt hierbei bewusst auf der Zusammenarbeit im Team, der Organisation des Projektes und der Anwendung agiler Vorgehensweisen und Praktiken entlang des Softwareentwicklungsprozesses. Aufbauend auf unseren Teaminternen Erfahrungen, Learnings und Expertisen aus dem Modul Software Engineering 1, wurden Arbeitsweisen, Rollenverständnis und eingesetzte Werkzeuge kritisch hinterfragt, angepasst und optimiert. Die folgenden Ausführungen basieren auf Retrospektiven, Sprint Reviews und weiterer Kommunikation innerhalb des Teams und sollen zentrale Probleme, deren abgeleiteten Erkenntnisse sowie große Erfolge mit deren jeweiligen Erfolgsfaktoren nachvollziehbar darstellen.
Im Projektverlauf konnten mehrere Maßnahmen identifiziert werden, die sich messbar positiv auf den Teamerfolg ausgewirkt haben.

== Erfolge
=== Erfolg 1 - Simplifizierung Arbeitsprozesse und der Arbeit mit dem Github-Project
Unter anderem kam es zu einer Professionalisierung, Standardisierung und vorallem Vereinfachung des Projekt Management durch Umstellung  von vielen verschiedenen Projektmanagementwerkzeugen auf hauptsächlich GitHub.
Aufgrund einer für unseren Anspruch unzureichenden Note in Software Engineering 1 entschied sich der Scrum Master über die Ferien das Projektmanagement anzupassen um dessen Leistung zu steigern.
Dies endete allerdings in einem überladenen Tool- Mix, in welchen eine in der Cloud befindliche Power Point- im Vorfeld von Meetings erstellt wurde und Überblick über die aktuellen Themen, nächsten Schritte, Probleme und Verantwortlichkeiten geben sollte. 
Zudem wurde das GitHub Board auch genutzt um aktuelle Task den entsprechenden Mitgliedern zuzuweisen. Hinzukommend nutzte das Team auch teilweise das Miro- Board und Discord sowie WhatsApp für  Meetings und Asynchrone Kommunikation. Der grundlegend gute Gedanke neue Technologien und Werkzeuge zu nutzen um die Zusammenarbeit zu verbessern, führte jedoch zu einer Überfrachtung und Verkomplizierung der Projektmanagement- Abläufe.
Ergebnis war immense Mehrarbeit und entsprechend zusätzlicher Zeitaufwand, da verschiedene Projektmanagement- Werkzeuge genutzt, gepflegt und geupdatet werden mussten. Es ergaben sich Inkonsistenzen zwischen den einzelnen Tools und Daten wurden redundant mehrmals niedergeschrieben. Die Mitglieder waren somit verwirrt und wussten nicht, welches Tool gerade die aktuellste Version beinhaltet.
Schon in Software Engineering 1 pflegten wir zudem nicht konsistent unser Git Hub Board und die darin enthaltenen Daten, sodass es auch innerhalb GitHub viele verschiedene und redundante Views, Labels und Task- Formate gab. Meist lag die Idee noch im ausprobieren und drauf loslegen, ohne sich vorher auf einheitliche Strukturen und Vorgehensweisen zu einigen.
Diese Inkonsistenz und unklaren Strukturen führte zu Planlosigkeit hinsichtlich der Abläufe und Umsetzungen im Projekt was Ineffizienz, Missverständnisse und Frustration innerhalb des Teams befeuerte.
Beispielsweise führten diese Arbeitsweisen dazu, dass entsprechend Tasks im Meeting per PowerPoint vergeben wurden aber nicht auf Github erstellt oder dem Team-Mitglied zugeordnet wurden. Teammitglieder mussten somit in PowerPoint sowie im Github-Project nach deren Aufgaben suchen was zum vergessen dieser führte. Zu viele (redundante) Labels resultierten in zu vielen Views und erschwerten die Übersichtlichkeit.
Um neue, präzisere und effizientere Strukturen zu erschaffen, beschlossen wir uns also in einem längeren Meeting, bestehende Inkonsistenzen zu bereinigen. Unsere Maßnahmen im Github waren zum einen die Reduktion der überflüssigen Views und Labels, die Einführung neuer und klarer Sichten in unserem Project- Board sowie die Vereinheitlichung von User Story und Task Formaten, wie auch die Ergänzung von Akzeptanzkriterien zu den entsprechenden Task. Ziel ist es, klare Strukturen zu schaffen welche verständliche Arbeitsabläufe ermöglichen und somit ein zielführendes Arbeiten im Team zu ermöglichen.
So wurden wichtige Sichten wie  ‚Sprint- Backlog -> Tasks from Userstories‘ oder ein ‚Product Backlog -> Userstories‘ angepast und vereinfacht um ein schnelles und übersichtliches Arbeiten mit diesen zu ermöglichen und somit besser nach gängigen Scrum- Methoden zu agieren. Die verbesserte Übersichtlichkeit und Verständlichkeit schaffte ein einheitliches Methodenverständnis unter allen Akteuren des Teams. Überflüssige Tools bzw. Medien wie PowerPoint wurden abgeschafft. Neben der nun minimierten Doppelpflege, Medienbrüchen und Verwirrung innerhalb des Teams, resultierte diese Maßnahme auch in einer transparenteren Arbeitsteilung und einen klaren Zuordnung von Task. Anders als in einer Power Point Tabelle, werden auf Git Hub die einzelnen Mitglieder explizit benachrichtigt, wenn Sie einem bestimmten Task zugeordnet wurden. Dies verhindert, dass Aufgaben übersehen oder vergessen werden. Die alleinige Nutzung von Github zur Zuordnung von Aufgaben ermöglicht einen Zentralen Ort, an dem alle Teammitglieder deren Aufgaben einsehen und bearbeiten können.  
Durch die Einführung von klareren und feingranulareren Labels, aber gleichzeitig der Minimierung der Labelanzahl auf das nötigste, weiß jedes Mitglied auch was für eine Art Task er genau abarbeiten muss. Hierfür nahmen wir eine Untergliederung in Story-, Documentation- und Implementation- Task vor. Während Story Task abgeleitete Programmierungs- bzw Implementations-Aufgaben im Code zur Erfüllung von den User Stories darstellen, adressieren Documentation Task konkrete Dinge die in die einzelnen Dokumenten niedergeschrieben werden müssen und Implementation Task dienen zur Bearbeitung allgemeiner Technischer Probleme und Aufgabenstellungen welche nicht direkt aus einer User Story abgeleitet wurden bzw. werden können. Wenn ein Mitglied nun einen Task assigned wird, weiß es somit intuitiv auf welche Problemdimension der jeweilige Task referenziert.  

//Nicht so geil
=== Erfolg 2 - Einführung strukturierter Scrum- Meetings & KPI’s
Neben der Optimierung des Projektmanagements wurde auch unsere Scrum- Arbeitsweisen strukturiert und weiterentwickelt. So veränderten wir unter anderem bestehende Meetingformate und verbesserten unsere wöchentlichen Meetings, in welchen nun eine effiziente Statusbesprechung und Planung von nächsten Schritten und Meilensteinen sowie Risiko und Problemevaluierung erfolgte. Zudem führten wir auch zu Beginn eines jeden Sprints ein Sprint- Planning- Meeting ein, in welchem der Product Owner im Vorfeld priorisierte User Stories einbrachte und mit dem  Entwicklerteam diese hinsichtlich ihrer Komplexität, Machbarkeit und ihres Augfwandes einschätzte. Zu Ende jedes Meetings fand eine Teaminterne Retrospektive statt, in welchem jedes Mitglied seine Zufriedenheit quantifizieren und begründen sollte in dem letzten Sprint. +
Ergänzend wurde ein Set an Key Performance Indikatoren eingefügt mit einem Happiness- Index, Kapazitätsübersicht sowie einer Task- Fortschrittsrate. Die KPI's dienten primär nicht ale kontrollinstrument, sondern sollten den Scrum Master eine Übersicht geben, um das Team hinsichtlich Belastung, Stimmung und Arbeitsfortschritte einschätzen zu können. 
Die Kapazitätsübersicht half uns hierbei grobe Tendenzen hinsichtlich verfügbarer Arbeitszeiten sichtbar zu gestalten, auch wenn studentische Einsatzmöglichkeiten naturgemäß schwanken und nur schwer planbar sind.  +
Zusammenfassend führten eine klare und effizientere Meetingstruktur, welche sich an gängigen Scrum- Best- Practices orientierte dazu, dass die Kommunikation und Planung erleichtert wurden. Meetings wurden nun strukturiert angegangen was dazu führte, dass weniger Zeit für nicht projektspezifische Diskussionen verwendet wurde wie in SE1.
Auch wenn die Metriken nicht alle Planungsprobleme lösen konnten, unterstützten Sie uns dabei Entwicklungen früher wahrzunehmen, zu quantifizieren und schon proaktiv auf Probleme reagieren zu können. 


//--Alter Versuch
Neben dem effizienteren Projektmanagement wurde auch die Scrum- Arbeitsweise nochmals überarbeitet und optimiert. Unter anderem wurde eine feste Meeting- Struktur eingeführt bzw. umgestaltet mit Weekly- Meetings welche in Ihrer Dauer auf 30- 60 min/Woche eingeschränkt wurden. Zudem wurden auch zu Beginn eines jeden Sprints ein ‚Sprint- Planning‘- Meeting eingeführt, in welchem vom Product Owner im Vorfeld priorisierte User Stories, die in den Sprint aufgenommen werden sollen vom Rest des Teams gewichtet werden und anschließend Task abgeleitet werden. Hierbei validiert ins besonders das Entwicklerteam die technische Umsetzung und Machbarkeit der einzelnen Stories. Dies stellt eine Orientierung an bestehenden Scrum- Prinzipien dar und ermöglicht eine effizientere Arbeitsweise innerhalb des Teams.
Zudem wurden Key Performance Indikatoren (KPI’s) eingeführt, welche kontinuierlich den Projekterfolg messen sollen. Als messbare Kennzahlen hierfür wurden vom Scrum Master ein ‚Hapiness Index‘, eine  ‚Task- Sucess- Rate‘ und eine ‚Capacity- Board‘ eingeführt. Der Hapiness- Score soll einen Überblick über die Zufriedenheit geben der einzelnen Teammitglieder. In jeder Retrospektive wird vom Scrum Master abgefragt, wie zufrieden die einzelnen Teammitglieder sind, im Hinblick auf das Projekt, dessen Fortschritt und die Zusammenarbeit innerhalb des Teams. Die Zufriedenheit soll hierbei quantifiziert werden was bedeutet, dass jedes Mitglied seine emotionale Stimmung anhand einer Skala von 1- 10 bewerten soll, wobei 10 die höchstmögliche emotionale Grundstimmung darstellt und 1 den worst- case abdeckt. In unserem Kapazitäten- Board, welches initial auf der Power Point gepflegt, dann jedoch auf Git Hub transferiert wurde, wird der Einsatz von den einzelnen Teammitgliedern für das Projekt je Woche gepflegt. In jeden Weekly wird somit vom Scrum Master erfasst wie viele Wochenstunden in der kommenden Woche, die einzelnen Akteure einsetzbar sind. Hierbei kann man sich entscheiden zwischen den Größen: Kein Einsatz, 1-2 h/Woche, 2-3h/Woche, 5-7h/Woche oder mehr als 7h/Woche entscheiden. Um ein Betrügen zu verhindern, wird im Nachgang jeweils überprüft, dass die erbrachte Arbeitsleistung der angegebenen Arbeitszeit in etwa entspricht und dass nicht konstant ein Akteur weniger arbeitet als andere. Für besonders motivierte Mitglieder, die mehr als 5 mal über 7 Stunden arbeiteten soll zu Ende des Projektes eine Belohnung in Form eines spendierten Essens erfolgen. Die Task- Fortschrittsrate gibt Überblick über die absolvierten Task pro Woche bzw. Sprint an. Sie zeigt klare Tendenzen hinsichtlich Effizienz und Organisation innerhalb des Teams an und lässt sich bei Bedarf auch auf einzelne Mitglieder runterbrechen.  Wichtig zu erwähne ist, dass die angeführten KPI’s keine direkte Kontrolle der Mitarbeiter beinhalten sollten, sondern lediglich den Scrum Master grobe Tendenzen innerhalb Arbeitsweise, Projektfortschritts und Betriebsklima geben sollen. Durch die Metriken sind unter anderem Überlastung und Demotivation der Arbeiter ersichtlich und eine bewusste Anpassung von Sprintumfängen und Aufgabenverteilung sowie besser Diskussionen in der Retrospektive möglich, da sich nun einzelne Gefühle quantifizieren lassen. 
//--
=== Erfolg 3 - Starker Teamzusammenhalt und klare Rollenverteilung
Als einen weiteren positiven Punkt lässt sich der grundsätzlich starke Teamzusammenhalt und die klare Rollenverteilung anbringen. Prinzipiell wurde innerhalb der Module SE1 und SE2 ein wertschätzendes Team mit klaren Regeln, Visionen und bis auf wenige Außnahmen  funktionierender Zusammenarbeit gebildet. Zudem wurde zu Beginn des Software Engineering 2 Modules auch erfolgreich ein neues und zugelostes Teammitglied integriert in die bestehenden Strukturen. Unsere Rollen sind klar verteilt und wurden in SE2 geschärft. So haben wir zu einem den Product Owner, welcher das Domänenwissen über Habits hat, sowie einen konkreten Überblick über Vision, User Stories und Features hat. Er priorisiert User Stories, welche anschließend in dem Sprint Planning- Meeting vor allem mit dem Entwickler- Team gewichtet und geschätzt werden hinsichtlich Komplexität und Aufwand. Der Scrum Master ist für die Organisation und Abwicklung aller Meetings vorhanden, sofern es keine spezialisierten Dev.- Team Meetings sind. Zudem ist er die unterstützende Instanz bei Konflikten und Problemen. Weitere Aufgaben von Ihm ist das grobe Projektcontrolling, auch hinsichtlich eingesetzter Techniken, also ob die Ist- Techniken mit den aus der Vorlesung und Praktikum gegebenen Soll- Techniken übereinstimmen. Zudem unterstützt er den auch den Product Owner. Das Dev.- Team ist für die konkrete Implementierung und Validierung von ‚Habitree‘ zuständig, wobei sich auch innerhalb dieses Teams spezifische Zuständigkeitsbereiche ergeben. So gibt es zum Beispiel Verantwortliche für das Backend, Frontend und das Testen. Ein Problem, was sich dabei ergibt sind Wissensinseln, die aber durch wöchentliche Meetings und einem Austausch innerhalb des gesamten Entwicklerteams ausgeglichen werden sollen. Die jetzige Beständigkeit unserer Teamstruktur baut auf verschiedenen Problemen auf, die in der Vergangenheit erfolgreich gemanagt wurden. Unter anderem bewältigten wir den Austritt eines Teammitgliedes noch in SE1,sowie  das ein Teammitglied nicht konstant arbeitet oder auch Kommunikationsprobleme durch verschiedene synchrone und asynchrone Kommunikationswege. Diese Hürden führten dazu, dass jeder seine Rolle und seinen Beitrag für das Team kennt. Alles in allem haben wir fast immer eine hohe Teilnehmerquote in Meetings und ein wertschätzendes Klima aufgebaut mit relativ flachen Hierarchien.


Die beschriebenen Erfolge zeigen, dass es dem Team im Verlauf von Software Engineering 2 gelungen ist Strukturen, Prozesse und Zusammenarbeit deutlich zu professionalisieren. Gleichzeitig legte aber auch gerade diese zunehmende Strukturierung und Optimierung Schwachstellen offen, die zuvor entweder verdeckt waren oder aufgrund geringer Komplexität keine wesentliche Rollen spielten.



== Misserfolge

Die beschriebenen Erfolge zeigen, dass es dem Team im Verlauf von Software Engineering 2 gelungen ist Strukturen, Prozesse und Zusammenarbeit deutlich zu professionalisieren. Gleichzeitig legte aber auch gerade diese zunehmende Strukturierung und Optimierung Schwachstellen offen, die zuvor entweder verdeckt waren oder aufgrund geringer Komplexität keine wesentliche Rollen spielten.
Im Folgenden werden daher drei zentrale Misserfolge bzw. Probleme beschrieben, die den Verlauf des Software Engineering- Projektes negativ beeinflussten, aus denen jedoch konkrete Maßnahmen und langfristige Erkenntnisse abgeleitet wurden, welche zur Behebung dieser Misstände in der Zukunft beitragen könnten.

=== Misserfolg 1 - Sprint Management und Planungsprobleme durch unregelmäßige und schwankende Kapazitäten der einzelnen Teammitglieder
Der erste Misserfolg bezieht sich auf unser Sprint- Management bedingt durch Planungsprobleme aufgrund schwankender Kapazitäten der einzelnen Mitglieder.  Unser Sprintmanagement stand im gesamten Modul vor wiederkehrenden Herausforderungen, die primär aus der studentischen Situation resultierten.  
So wurde unser Projekt nicht in Vollzeit durchgeführt, sondern es entstand parallel zu mehreren anderen Modulen, Deadlines, Praktika oder anderen Projekten.  Somit variierten die Kapazitäten der einzelnen Mitarbeiter zwischen und innerhalb der einzelnen Wochen erheblich.  Zu Beginn jedes Sprints priorisierten wir im Sprint Planning - Meeting User Stories, zerlegten diese in konkrete Aufgaben und nahmen sie in das Sprint Backlog auf. Zudem fragte der Scrum Master jede Woche, auch im Zuge der KPI- Auswertung, die Einsatzfähigkeit in Stunden der Mitglieder ab (z.B.: innerhalb des Kapazitätsboards in Git Hub). Trotz dieser Workflows zeigten sich jedoch Probleme innerhalb der eigentlichen Umsetzung.  So konnten wir in einigen Iterationen deutlich mehr leisten als geplant, sodass der Sprint nach zwei Wochen schon vollständig abgeschlossen war. In anderen Sprints hatten wir teilweise weniger Zeit als erwartet, sodass nicht alle geplanten Task abgearbeitet werden konnten.  Dies führte zu einer Divergenz vom theoretischen Scrum- Timeboxing und der Anwendung der Scrum- Praktiken in dem studentischen Alltag. 
Dies führte dazu, dass wir das Sprint- Framework leicht abändern mussten um auf die sich schnell ändernde  studentische Umwelt angepasst zu sein. Wenn ein Sprint deutlich vorzeitig abgeschlossen wurde mit all seinen Aufgaben (als Zeitpunkt setzten wir 10 Tage vor dem eigentlichen Ende an), führten wir ein Refill- Meeting ein, um neue Stories aus dem Product Backlog aufzunehmen.  Wie im eigentlichen Sprint Planning- Meeting wurden die entsprechenden Product Backlog Items erst vom Product Owner priorisiert, dann innerhalb des Teams geschätzt hinsichtlich Komplexität und Aufwand und anschließend wurden konkrete Task abgeleitet. 
Das Ziel sollte die Vermeidung unnötiger Leerlaufzeit und die kontinuierliche Steigerung des Geschäftswertes sein. 
Wurden Aufgaben bis Sprint Ende nicht abgeschlossen, dann mussten diese aus dem alten Sprint entfernt werden, erneut refined und für den nächsten Sprint eingeplant werden.  
Die bewusste Abweichungen von den in der Vorlesung geschilderten Scrum- Prinzipien barg auch einige Nachteile. So verschwommen teilweise die Sprintgrenzen, was die Transparenz, vor allem auch gegenüber Stakeholdern in Sprint Reviews negativ beeinflusste. Auch die Planbarkeit und strategische Steuerung des Projektes wurde komplexer.  
Wir haben gelernt, dass Sprints im universitären Umfeld anders funktionieren als in Vollzeit- Produktteams. Während in Scrum  formell davon ausgegangen wird, dass Teams eine annährend konstante Velocity besitzen, sind studentische Teams eher volatil und somit tendenziell schlechter planbar. In der beruflichen Praxis ist es selten der Fall, dass z.B.: Mitarbeiter nur für 3 bis 10 Stunden die Woche auf einem Projekt eingesetzt sind. Unser adaptives Vorgehen weicht zwar von einigen gängigen Scrum- Best- Pratices ab (u.a. dass Sprints nicht nachgefüllt werden sollten mit weiteren PBI’s), ergab jedoch aus Projektsicht einen sinnvollen Kompromiss. 
In zukünftigen Projekten würden wir Sprints bewusst kürzer halten (wie auch schon zu Ende gemacht, da unser Sprint 3 nur für eine Dauer von 14 Tagen angedacht war) , da sich auf kürzere Zeit kapazitive Schwankungen tendenziell geringer ausfallen. Zudem würden wir dieses Thema auch schon frühzeitig in unser Risikoboard aufnehmen.  Pufferzeiten in Sprints, würden wir vor allem mit der Beseitigung von Bugs, Dokumentations- Aufgaben und Verbesserung unserer Architektur und unseres Codes verbringen. 

=== Misserfolg 2 - Entstehung von Inselwissen, aufgrund fehlendes horizontalen Wissenstransfers
Ein weiterer Misserfolg besteht in der Entstehung von Inselkompetenzen und einen fehlenden horizontalen Wissenstransfer. Mit Fortschreiten des Projektes fand eine zunehmende Spezialisierung des Teams in klar voneinander abgegrenzte Domänen statt, gemäß Ihrer Rollen und Verantwortlichkeiten. Dies ist grundsätzlich sinnvoll, gerade bei kleineren Teamgrößen, führt jedoch zwangsläufig zu einer Entstehung von Wissensinseln.  Während der Scrum- Master primär für Meeting Planung, Prozessüberwachung und die Sicherstellung der agilen Arbeitsweise verantwortlich war, kümmerte sich der Product Owner um das Stakeholdermanagement sowie die Priorisierung von User Stories. Das Entwicklerteam untergliederte sich in weitere Subdomänen, so gab es jeweils verantwortliche für das Frontend, Backend und die Testgestaltung. Durch diese Spezialisierung kam es dazu, dass die Teammitglieder über die Sprints hinweg sich immer tiefer in Ihre jeweiligen Subdomänen einarbeiteten ohne das eine ganzheitlicher horizontaler Wissenstransfer entstand. Fielen Teammitglieder nun beispielsweise Krankheitsbedingt aus, konnten Tasks entweder gar nicht oder maximal unzureichend von anderen Teammitglieder umgesetzt werden. Zum Beispiel als unser Datenbankverantwortliche über zwei Wochen krankheitsbedingt ausfiel, konnten Features nicht vollständig implementiert werden weil die Umsetzung in der Datenbank nicht implementiert werden konnte zumindest nicht mit zufriedenstellender Qualität. Das Team war dadurch nur eingeschränkt in der Lage flexibel auf zeitkritische Risiken zu reagieren, welche einen Ausfall einzelner Mitglieder adressierten. Wenn dennoch eine Einarbeitung in fremde Themengebiete erfolgte, bestand ein hoher Einarbeitungsaufwand, da die Interaktion zwischen den einzelnen Teammitgliedern nur an Schnittstellen statt fand. 
Zukünftig könnte man vermehrt Pair Programming einführen, um Wissen direkt zwischen den Rollen auszutauschen. Zudem muss ein noch stärkerer Fokus auf eine saubere, konsistente und nicht zu überladene Dokumentation gelegt werden, sodass man sich Rollenwissen direkt anlesen kann. Zudem könnte man auch Backup- Rollen definieren, sodass jeder Zuständigkeitsbereich von mindestens zwei Gruppenmitglieder prinzipiell erledigt werden kann. 
Wir erkannten, dass technische Spezialisierung zwar effizient erscheint, jedoch langfristig zu strukturellen Risiken führen kann. Um eine nachhaltige Arbeitsweise im Team hervorbringen zu können, muss Wissen aktiv geteilt und ausgetauscht werden, statt sich nur in seine Domäne einzuarbeiten. Software Engineering ist Teamarbeit und bedarf neben technischen auch eine Vielzahl sozialer Kompetenzen.


=== Misserfolg 3 - Scheitern selbstorganisierter Zusammenarbeit bei geringer individueller Motivation eines Teammitgliedes
Ein weiterer Misserfolg zeigte sich darin, dass 
selbstorganisierter Zusammenarbeit trotz einer grundsätzlich stabilen Teamstruktur deutlich an ihre Grenzen stieß, sobald die individuelle Motivation und Einsatzbereitschaft einzelner Mitglieder variierte.  +
So wurde bereits gegen Ende von Software Engineering 1 deutlich, dass einzelne Teammitglieder unterschiedlich stark zur Gruppenleistung beitrugen. 
Diese Entwicklung setzte sich in Software Engineering 2 fort und wurde mit wachsendem Projektumfang noch stärker ersichtlich. +
Trotz einer allgemein positiven Teamdynamik nahm u.a. ein Mitglied wenn überhaupt nur passiv an den Meetings teil und 
erledigte seine Task nur mit geringer Qualität. 
So mussten Aufgaben wie Wireframes, Sequenzdiagramme oder auch Teile des Benutzerhandbuches von anderen Mitgliedern entweder verbessert oder gänzlich übernommen werden um den internen Qualitätsanforderungen zu entsprechen.
// ---Versuch 1
Auch mit dem Stakeholdermanagement gab es zeitweise Probleme, sodass sich Features teilweise von den entsprechenden Entwicklern selber konstruiert werden mussten.
//--- 
Verstärkt wurde diese Situation dadurch, dass unsere Teamkultur auf flachen Hierachien, Freiwilligkeit sowie Vertrauen basierte. Solche Strukturen sind wirkungsvoll, solange Motivation, Arbeitsweise und Wissen aller Mitarbeiter relativ ähnlich sind. Divergiert der Reifegrad der Mitarbeiter jedoch signifikant, stößt ein demokratischer Führungsstil an seine Grenzen. 
//--- Versuch 2
So kam es zum Beispiel auch in der Stakeholderkommunikation zeitweise zu Verzögerungen.
//---
Um den Projektfortschritt dennoch sicherzustellenb, passten wir unseren Führungsstil situativ an, orientiert am Reifegradmodell von Hersey und Blanchard. Auch wenn uns bewusst ist, dass dies ein Stilbruch mit gängigen Scrum- Methoden ist, führten wir so für Arbeiter mit geringerer Motivation verbindliche Prozesse ein, mit klar definierten Aufgaben und Deadlines. Dies zeigte kurzfristig Verbesserung, konnte aber dennoch nicht die fehlende Motivation einzelner Arbeiter verbessern.  +
Selbstorganisation ist nicht in allen Teamkonstellationen und unter allen Umgebungsvariablen gleichmäßig einsetzbar. Dies zeigte auch ein Wachstum in dem Bedarf vieler Teammitglieder nach einer stärkeren Taskdelegation mit klareren zeitlichen Rahmen im Zuge des steigenden Projektdruckes zu Semesterende hin. +
Für zukünftige Projekte nehmen wir uns mit Probleme frühzeitig offen anzusprechen und Gründe für die fehlende Motivation aktiv zu klären. Zudem bedarf es gleich von Anfang an klaren Rollen, Erwartungen und Eskalationsprozessen um transparenz zu schaffen und die Grundidee der partizipativen Zusammenarbeit maximal umsetzen zu können.   



//Alte Version
Unser letzter Misserfolg bezieht sich auf anhaltenden Schwierigkeiten mit einem Teammitglied, deren Ursprung bereits in Software-Engineering 1 lag und sich über den gesamten Zeitraum von Software- Engineering 2 deutlich abzeichnete. Trotz der grundsätzlich positiven Dynamik im Team stellte dieses Mitglied die Grenzen flacher Hierarchien und selbstogranisierter, demokratischer Arbeitsweisen wiederholt auf die Probe. 
Dies zeigte sich vor allem in Form von niedriger Motivation, passiven Verhalten in Meetings und nicht angemeldetes Fehlen in Meetings etc. 
Zugewiesene oder vereinbarte Aufgaben wie z.B.: die Erstellung von Wireframes oder Sequenzdiagramme und die Anfertigung eines Benutzerhandbuches wurden teilweise gar nicht, und wenn nur oberflächlich oder mit KI- generierten Inhalten eingereicht. Da dieses Verhalten in keiner Weise unseren internen Qualitätsanforderungen entspricht, entstand ein aktiver Schaden in unserer Arbeitskultur, da teilweise unzureichende Arbeit weiterverarbeitet oder von anderen Mitgliedern zeitaufwendig verbessert werden musste. 
///// //// ////
Da die Arbeitskultur im Team auf Freiwilligkeit, Selbstständigkeit und Zuverlässigkeit basiert, ist ein gewisses Engagement jedes einzelnen Voraussetzung. Problematisch ist dies, wenn die Ansprüchen an die Note und die Projektarbeit der Mitglieder stark divergieren.
/////// //// //// //// ////
Diese Kultur entspricht der Arbeitsweise der Mehrheit des Teams, jedoch nicht für dieses spezifische Mitglied. Trotz zahlreicher Versuche, intrinsische Motivation zu fördern (z. B.: Unterstützung, flexible Aufgabenauswahl oder nettes verweisen auf unerledigte Task), kam es zu keiner Verbesserung. Die Arbeitsweise dieses Mitglieds blieb bis zum Ende des Projektes auf ein absolutes Minimum beschränkt. Erst durch einen deutlichen Führungswechsel, der von gängigen Methoden der agilen und iterativen Entwicklung abweicht, gelang es uns ein Mindestmaß an Qualität und Pünktlichkeit in seine Arbeit zu bekommen. Angelehnt an das Reifegradmodell von Hersey und Blanchard versuchten wir nur bei dem Mitglied eine erhöhte Aufgabenorientierung vorzunehmen und verbindliche Strukturen zu definieren. Diese beinhalteten eine klare Aufgabenverteilung, verbindliche Deadlines  sowie eine Androhung der Eskalation an Professor oder Coach, wenn sich das Verhalten auch langfristig nicht bessert. Diese Maßnahmen führten kurzfristig zu einer minimalen Verbesserung der Arbeitsergebnisse, änderten jedoch nichts an der Grundeinstellung der Person. Aufgaben wurden nach wie vor nur kurz vor knapp abgegeben, und größtenteils mit KI bearbeitet und auch die Beteiligung in Meetings fand nur sehr sporadisch statt. 
Diese Erfahrungen zeigten uns deutlich, dass Selbstorganisation nicht als Führungsprinzip für alle Teammitglieder geeignet ist, vor allem nicht über einen längeren Zeitraum. Mit zunehmendem Projektstress stieg der Wunsch und die Notwendigkeit das alle Mitglieder zumindest nach derem Möglichkeiten ihren Beitrag leisten, da die Motivation den Mangelnden Beitrag anderer auszugleichen sank.
Trotz des Wandels unseres Führungsstiles, versuchten wir auch zu Ende hin maximale Partizipation aller Mitglieder zu ermöglichen, durch regelmäßige Meetings und wenig Zwang bei der Aufgabenvergabe. Dennoch blieb die Mitarbeit des betroffenen Teammitgliedes bis zum Schluss hin unzuverlässig.  
Zukünftig müsste man schon direkt, wenn sich ein solches Problem abzeichnet mit dem entsprechenden Mitglied kommunizieren und genaue Gründe für seine Demotivation ermitteln. Zudem sollte man einen klar strukturierten Eskalationsprozess erbauen und keine Scheu besitzen diesen umzusetzen.  Teammitglieder mit einen geringeren Reifegrad sei es aus geringer Motivation oder fehlender Kompetenz müssen schon zu Beginn an stark in das Team eingebettet werden und benötigen eine klare Erwartungsklärung zu Ihren entsprechenden Rollen und Zuständigkeiten. 



=== Finale Version:

Im Rahmen des Modules Software Engineering 2 reflektiert Team 3A den Verlauf der gemeinsamen Projektarbeit an der Habit-Tracking App „Habitree“. Der Fokus dieser Reflexion liegt hierbei bewusst auf der Zusammenarbeit im Team, der Organisation des Projektes und der Anwendung agiler Vorgehensweisen und Praktiken entlang des Softwareentwicklungsprozesses. Aufbauend auf unseren teaminternen Erfahrungen, Learnings und Expertisen aus dem Modul Software Engineering 1, wurden Arbeitsweisen, Rollenverständnis und eingesetzte Werkzeuge kritisch hinterfragt, angepasst und optimiert. Die folgenden Ausführungen basieren auf Retrospektiven, Sprint Reviews und weiterer Kommunikation innerhalb des Teams. Die Reflexion zeigt nachvollziehbar einerseits zentrale Probleme verbunden mit daraus abgeleiteten Erkenntnissen, andererseits große Erfolge mit deren jeweiligen Erfolgsfaktoren.

Im Projektverlauf konnten mehrere Maßnahmen identifiziert werden, die sich messbar positiv auf den Teamerfolg ausgewirkt haben.
Die Reduzierung von vielen verschiedenen Projektmanagementwerkzeugen auf ein wesentliches, GitHub, bewirkte eine Professionalisierung, Standardisierung und vor allem Vereinfachung des Projektmanagements. Aufgrund einer für unseren Anspruch unzureichenden Note in Software Engineering 1 entschied sich der Scrum Master während der vorlesungsfreien Zeit, das Projektmanagement anzupassen, um dessen Leistung zu steigern. Dies führte jedoch zu einem überladenen Tool-Mix. Eine im Vorfeld von Meetings erstellte, in der Cloud befindliche PowerPoint in der Cloud sollte einen Überblick über die aktuellen Themen, nächsten Schritte, Probleme und Verantwortlichkeiten geben. Außerdem wurde das GitHub Board genutzt, um aktuelle Tasks den entsprechenden Mitgliedern zuzuweisen. Hinzukommend nutzte das Team auch teilweise das Miro Board und die Discord App sowie WhatsApp für seine Meetings und asynchrone Kommunikation. Der grundlegend gute Gedanke, neue Technologien und Werkzeuge zu nutzen, um die Zusammenarbeit zu verbessern, verursachte jedoch eine Überfrachtung und Verkomplizierung der Abläufe im Projektmanagement. Daraus ergaben sich eine immense Mehrarbeit mit dem entsprechend zusätzlichen Zeitaufwand, weil verschiedene Werkzeuge zum Projektmanagement genutzt, gepflegt und geupdatet werden mussten. Daraus resultierten Inkonsistenzen zwischen den einzelnen Tools. Außerdem wurden Daten redundant mehrmals niedergeschrieben. Es herrschte Unklarheit unter den Akteuren, welches Tool gerade die aktuellste Version beinhaltete. Zudem hatten wir in Software Engineering 1 nicht konsistent unser GitHub Board und die darin enthaltenen Daten gepflegt, sodass es auch innerhalb GitHub viele verschiedene und redundante Views, Labels und Task Formate gab. Vorherige Ansprachen zur Festlegung einheitlicher Strukturen und Vorgehensweisen fehlten. Diese Inkonsistenz und unklaren Strukturen führten zu Planlosigkeit hinsichtlich der Abläufe und Umsetzung des Projekts was Ineffizienz, Missverständnisse und Frustration innerhalb des Teams befeuerte. Beispielsweise führten diese Arbeitsweisen dazu, dass entsprechende Tasks im Meeting per PowerPoint vergeben wurden, ohne sie auf GitHub einzustellen und den Teammitgliedern sichtbar zuzuordnen. Dadurch wurden Aufgaben nicht gefunden und damit nicht erledigt. Zu viele (redundante) Labels mündeten in zu viele Views und erschwerten die Übersichtlichkeit. Um neue, präzisere und effizientere Strukturen zu erschaffen, beschlossen wir in einem längeren Meeting, bestehende Inkonsistenzen zu beseitigen. Unsere Maßnahmen betrafen einerseits die Reduzierung überschüssiger Views und Labels im GitHub, die Einführung neuer und klarer Sichten in unserem Project Board, die Vereinheitlichung der User Story - und Task Formate sowie die Ergänzung von Akzeptanzkriterien zu den entsprechenden Tasks. Das Ziel bestand in der Schaffung klarer Strukturen, um verständliche Arbeitsabläufe und ein schnelleres und übersichtliches Arbeiten, somit ein zielführendes Arbeiten im Team zu ermöglichen und besser nach gängigen Scrum Methoden zu agieren. So wurden wichtige Sichten wie Sprint- Backlog -> Tasks from User Stories oder ein Product Backlog -> User Stories angepasst und vereinfacht. Die verbesserte Übersichtlichkeit und Verständlichkeit schaffte ein einheitliches Methodenverständnis unter allen Akteuren des Teams. Überflüssige Tools bzw. Medien wie PowerPoint wurden abgeschafft. Neben der nun minimierten Doppelpflege, Medienbrüchen und Verwirrung innerhalb des Teams, führte diese Maßnahme auch zu einer transparenteren Arbeitsteilung und einer klaren Zuordnung von Tasks. Anders als in einer PowerPoint-Tabelle, erfolgte auf GitHub eine explizite Benachrichtigung der einzelnen Mitglieder über Aufgaben. Dies verhinderte, dass Aufgaben übersehen oder vergessen wurden. Die alleinige Nutzung von GitHub zur Zuordnung von Aufgaben schuf einen zentralen Ort, an dem alle Teammitglieder ihre Aufgaben einsehen und bearbeiten konnten. Durch die Einführung klarer und feingranularer Labels und die gleichzeitige Minimierung der Labelanzahl beeinflusste die Kenntnis über anstehende Tasks und deren zeitnahes Abarbeiten maßgeblich positiv. Hierfür nahmen wir eine Untergliederung in Story-, Documentation- und Implementation-Task vor. Während Story Tasks abgeleitete Programmierungs- bzw. Implementations-Aufgaben im Code zur Erfüllung von den User Stories darstellten, beinhalteten Documentation -Tasks konkrete Fakten, die in die einzelnen Dokumente eingebunden werden mussten. Implementation-Task dienten zur Bearbeitung allgemeiner technischer Probleme und Aufgabenstellungen, die nicht direkt aus einer User Story abgeleitet wurden bzw. werden konnten. Wenn ein Mitglied nun einen Task assigned wurde, wusste es somit intuitiv, auf welche Problemdimension der jeweilige Task sich referenziert.

Neben der Optimierung des Projektmanagements wurden auch unsere Scrum-Arbeitsweisen strukturiert und weiterentwickelt. So veränderten wir unter anderem bestehende Meeting-Formate und verbesserten unsere wöchentlichen Meetings, in denen nun eine effiziente Statusbesprechung und Planung der nächsten Schritte und Meilensteine, eine Abwägung von Risiken und eine Problemevaluierung erfolgte. Zudem führten wir auch zu Beginn eines jeden Sprints ein Sprint Planning-Meeting ein, in welchem der Product Owner im Vorfeld priorisierte User Stories einbrachte und mit dem Entwicklerteam diese hinsichtlich ihrer Komplexität, Machbarkeit und ihres Aufwandes einschätzte. Am Meeting-Ende fand jeweils eine teaminterne Retrospektive statt, in der jedes Mitglied seine Zufriedenheit quantifizieren und begründen sollte. Ergänzend wurde ein Set an Key Performance Indicators mit einem Happiness Index, Kapazitätsübersicht sowie einer Task- Fortschrittsrate eingefügt. Die KPIs dienten primär nicht als Kontrollinstrument, sondern sollten vielmehr dem Scrum Master zur besseren Einschätzung des Teams bezüglich Belastung, Stimmung und Arbeitsfortschritte ermöglichen. Die Kapazitätsübersicht half uns hierbei, grobe Tendenzen hinsichtlich verfügbarer Arbeitszeiten sichtbar zu gestalten, auch wenn studentische Einsatzmöglichkeiten naturgemäß schwanken und nur schwer planbar sind.  
Zusammenfassend führten eine klare und effizientere Meeting-Struktur, die sich an gängigen Scrum Best Practices orientierte, dazu, dass die Kommunikation und Planung erleichtert wurden. Strukturierte Meetings führten dazu, dass wesentlich weniger Zeit für nicht projektspezifische Diskussionen verwendet wurde als in SE 1. Auch wenn die Metriken nicht alle Planungsprobleme lösen konnten, unterstützten Sie uns dabei, Entwicklungen früher wahrzunehmen, zu quantifizieren und proaktiv auf Probleme reagieren zu können. 
 
Ein weiterer positiver Aspekt, der maßgeblich zum Erfolg der Projektarbeit beitrug, bestand im grundsätzlich starken Zusammenhalt des Teams mit der klaren Rollenverteilung. Prinzipiell bildete sich innerhalb der Module SE 1 und SE 2 ein Team, das sich, bis auf wenige Ausnahmen, gegenseitige Wertschätzung entgegenbrachte, nach klaren Regeln agierte, gemeinsame Visionen formulierte und erfolgversprechend zusammenarbeitete. Zudem wurde zu Beginn des Software Engineering 2 Modules auch erfolgreich ein neues, zugelostes, Teammitglied in die bestehenden Strukturen integriert. Unsere Rollen warten klar verteilt und wurden in SE 2 geschärft. Unser Product Owner verfügte über das Domänenwissen hinsichtlich Habits und hatte einen konkreten Überblick über Visionen, User Stories und Features. Er priorisierte User Stories, welche anschließend in dem Sprint Planning Meeting vor allem mit dem Entwicklerteam hinsichtlich Komplexität und Aufwand gewichtet und bewertet wurden. Der zuverlässige Scrum Master war für die Organisation und Abwicklung aller Meetings zuständig, sofern es sich nicht um spezialisierte Dev.-Team Meetings handelte. Zudem stellte er die unterstützende und ausgleichende Instanz bei Konflikten und Problemen dar. Seine weiteren Aufgaben bestanden im groben Projektcontrolling, auch hinsichtlich eingesetzter Techniken. Er sicherte die Übereinstimmung der Ist-Techniken mit den aus der Vorlesung und dem Praktikum vermittelten Soll- Techniken. Zudem unterstützte er den Product Owner. Das Dev.-Team war für die konkrete Implementierung und Validierung von Habitree zuständig. Innerhalb dieses Teams ergaben sich spezifische Zuständigkeitsbereiche ergaben, zum Beispiel die Verantwortlichkeiten für das Backend, Frontend und das Testen. Dabei zeigte sich das Problem der Wissensinseln. Dank der wöchentlichen Meetings und einem Austausch innerhalb des gesamten Entwicklerteams konnten diese erfolgreich behoben werden. Die jetzige Beständigkeit unserer Teamstruktur baute auf verschiedenen Problemen auf, die in der Vergangenheit erfolgreich gemanagt wurden. Unter anderem bewältigten wir den Austritt eines Teammitgliedes noch in SE 1, überzeugten ein nicht konstant arbeitendes Teammitglied von der Notwendigkeit kontinuierlichen Arbeitens und behoben Kommunikationsprobleme durch verschiedene synchrone und asynchrone Kommunikationswege. Diese überwundenen Hürden führten dazu, dass jeder seine Rolle und seinen Beitrag für das Team kannte und erbrachte. Fast alle unserer Meetings zeichneten sich durch eine hohe Teilnehmerzahl und ein stets wertschätzendes Klima mit relativ flachen Hierarchien aus.
 
Unsere Teamarbeit bestand jedoch nicht nur aus erfolgreichen Erlebnissen, auch Misserfolge prägten die Arbeit. Einen Misserfolg verzeichnete das Sprint Management bedingt durch Planungsprobleme aufgrund schwankender zeitlicher Kapazitäten der einzelnen Mitglieder.  Unser Sprint Management stand im gesamten Modul vor wiederkehrenden Herausforderungen, die primär aus der studentischen Situation resultierten. So wurde unser Projekt nicht in Vollzeit durchgeführt, sondern parallel zu verschiedenen anderen Modulen, Deadlines, Praktika und anderen Projekten. Somit variierten die zeitlichen Verfügbarkeiten der einzelnen Mitarbeiter zwischen und innerhalb der einzelnen Wochen erheblich. Zu Beginn jedes Sprints priorisierten wir User Stories im Sprint Planning-Meeting, zerlegten diese in konkrete Aufgaben und nahmen sie in das Sprint Backlog auf. Zudem erfragte der Scrum Master wöchentlich, auch im Zuge der KPI-Auswertung, die Einsatzfähigkeit der Mitglieder in Stunden (z.B.: innerhalb des Kapazitätsboards in GitHub). Trotz dieser Workflows zeigten sich jedoch Probleme innerhalb der eigentlichen Umsetzung. So konnten wir in einigen Iterationen deutlich mehr leisten als geplant, sodass der Sprint nach zwei Wochen schon vollständig abgeschlossen war. Andere Sprints verliefen langsamer, als erwartet, sodass nicht alle geplanten Tasks abgearbeitet wurden. Dies führte zu einer Divergenz zwischen dem theoretischen Scrum Timeboxing und der Anwendung der Scrum Praktiken im studentischen Alltag. Daher änderten wir das Sprint- Framework leicht ab, um auf die sich schnell ändernde studentische Umwelt angepasst zu sein. Wurde ein Sprint mit all seinen Aufgaben deutlich vorzeitig abgeschlossen (als Zeitpunkt setzten wir 10 Tage vor dem eigentlichen Ende an), führten wir ein Refill-Meeting ein, um neue Stories aus dem Product Backlog aufzunehmen.  Wie im eigentlichen Sprint Planning-Meeting wurden die entsprechenden Product Backlog Items erst vom Product Owner priorisiert, dann innerhalb des Teams hinsichtlich Komplexität und Aufwand gewichtet. Anschließend wurden konkrete Tasks abgeleitet. Das Ziel bestand darin, unnötige Leerlaufzeit zu vermeiden und den Geschäftswert kontinuierlich zu steigern. Nicht bis zum Sprint-Ende abgeschlossene Aufgaben wurden aus dem alten Sprint entfernt, erneut refined und für den nächsten Sprint eingeplant. Die bewusste Abweichung von den in der Vorlesung geschilderten Scrum Prinzipien barg auch einige Nachteile. So verschwommen teilweise die Sprint-Grenzen, was die Transparenz, vor allem auch gegenüber Stakeholdern in Sprint Reviews negativ beeinflusste. Auch die Planbarkeit und strategische Steuerung des Projektes wurde komplexer. Wir lernten, dass Sprints im universitären Umfeld anders funktionieren als in Vollzeit- Produktteams. Während in Scrum formell davon ausgegangen wird, dass Teams eine annährend konstante Velocity besitzen, sind studentische Teams eher volatil und somit tendenziell schlechter planbar. In der beruflichen Praxis ist es selten der Fall, dass z.B.: Mitarbeiter nur für 3 bis 10 Stunden pro Woche für ein Projekt eingesetzt sind. Unser adaptives Vorgehen wich zwar von einigen gängigen Scrum Best Pratices ab (u.a. dass Sprints nicht mit weiteren PBIs nachgefüllt werden sollten), ergab jedoch aus Projektsicht einen sinnvollen Kompromiss. In zukünftigen Projekten würden wir Sprints bewusst kürzer halten. So setzten wir für unseren letzten Sprint nur eine Dauer von 14 Tagen an. Wir bemerkten, dass kapazitive Schwankungen auf kürzere Zeit tendenziell geringer ausfallen. Zudem würden wir dieses Thema auch schon frühzeitig in unser Risikoboard aufnehmen. Entstandene Pufferzeiten in Sprints würden wir vor allem mit der Beseitigung von Bugs, der Erledigung von Dokumentationsaufgaben und der Verbesserung unserer Architektur und unseres Codes verbringen.
Ein weiterer Misserfolg bestand in der Entstehung von Inselkompetenzen und eines fehlenden horizontalen Wissenstransfers. Im Verlauf des Projektes fand eine zunehmende Spezialisierung des Teams in klar voneinander abgegrenzte Domänen, gemäß der Rollen und Verantwortlichkeiten, statt. Gerade bei kleineren Teamgrößen empfanden wir diesen Aspekt sinnhaft, allerdings führte er zur Entwicklung von Spezialkompetenzen, Wissensinseln. Jedes Teammitglied ging in seiner Aufgabe auf und perfektionierte sich. Der Scrum Master war primär für die Meeting Planung, Prozessüberwachung und die Sicherstellung der agilen Arbeitsweise verantwortlich, der Product Owner kümmerte sich um das Stakeholdermanagement sowie die Priorisierung von User Stories. Das Entwicklerteam untergliederte sich in weitere Subdomänen. Es gab jeweils Verantwortliche für das Frontend, Backend und die Testgestaltung. Diese Spezialisierung bewirkte, dass die Teammitglieder über die Sprints hinweg sich immer tiefer in ihre jeweiligen Subdomänen einarbeiteten. Ein ganzheitlicher horizontaler Wissenstransfer fand aber nicht statt. Das führte zu Problemen. Im Krankheitsfall eines Teammitglieds konnten Tasks entweder gar nicht oder nur unzureichend von anderen Teammitglieder umgesetzt werden. Der zweiwöchige krankheitsbedingte Ausfall unseres Datenbankverantwortlichen verursachte, dass Features nicht vollständig implementiert werden konnten. Der Grund dafür lag darin, dass andere Teammitglieder die Implementierung in die Datenbank aufgrund unzureichender Kenntnisse nur mit unzufriedenstellender Qualität umsetzen konnten. Das Team war dadurch nur eingeschränkt in der Lage, flexibel auf zeitkritische Risiken zu reagieren, welche aufgrund des Ausfalls einzelner Mitglieder hervorgerufen wurden. Die Einarbeitung in fremde Themengebiete erforderte einen hohen Einarbeitungsaufwand, da die Interaktion zwischen den einzelnen Teammitgliedern nur an Schnittstellen zwischen Verantwortlichkeitsbereichen stattfand.
Um dieses Problem zu vermeiden, könnte man künftig Pair Programming einführen, um Wissen direkt zwischen den Rollen auszutauschen. Zudem muss ein noch stärkerer Fokus auf eine saubere, konsistente und prägnante Dokumentation gelegt werden, sodass man sich Rollenwissen direkt anlesen kann. Des Weiteren könnte man Backup-Rollen definieren, sodass jeder Zuständigkeitsbereich von mindestens zwei Gruppenmitglieder prinzipiell erledigt werden kann. Wir erkannten, dass technische Spezialisierung zwar effizient erscheint, jedoch langfristig zu strukturellen Risiken führen kann. Um eine nachhaltige Arbeitsweise im Team hervorzubringen, muss Wissen unter den Mitgliedern aktiv geteilt und ausgetauscht werden. Software Engineering ist Teamarbeit und bedarf neben technischen auch eine Vielzahl sozialer Kompetenzen.
Ein weiterer Misserfolg zeigte sich in der selbstorganisierten Zusammenarbeit. Schwankende individuelle Motivation und Einsatzbereitschaft einzelner Mitglieder beeinflusste die effektive, erfolgreiche Zusammenarbeit, trotz einer grundsätzlich stabilen Teamstruktur, negativ. Bereits gegen Ende von Software Engineering 1 zeigte sich deutlich, dass einzelne Teammitglieder unterschiedlich stark zur Gruppenleistung beitrugen. Diese Entwicklung setzte sich in Software Engineering 2 fort und wurde mit wachsendem Projektumfang noch stärker ersichtlich. Obwohl wir die allgemeine Teamdynamik positiv empfanden, nahm ein Mitglied nahm, wenn überhaupt, nur passiv an den Meetings teil und erledigte seine Tasks nur in geringer Qualität. So mussten Aufgaben wie Wire Frames, Sequenzdiagramme oder auch Teile des Benutzerhandbuchs von anderen Mitgliedern entweder verbessert oder gänzlich übernommen werden, um den teaminternen Qualitätsanforderungen zu entsprechen. Verstärkt wurde diese Situation dadurch, dass unsere Teamkultur auf flachen Hierarchien, Freiwilligkeit sowie Vertrauen basierte. Derartige Strukturen sind wirkungsvoll, solange Motivation, Arbeitsweise und Wissen aller Mitarbeiter vergleichbar sind. Divergiert der Reifegrad der Mitarbeiter jedoch signifikant, stößt ein demokratischer Führungsstil an seine Grenzen. Um den Projektfortschritt dennoch sicherzustellen, passten wir unseren Führungsstil situativ an. Dafür orientierten wir uns am Reifegradmodell von Hersey und Blanchard. Uns war bewusst Stilbruch mit gängigen Scrum Methoden. Wir führten für Teammitglieder mit geringerer Motivation verbindliche Prozesse mit klar definierten Aufgaben und Deadlines ein. Dies zeigte kurzfristig Verbesserung, konnte aber dennoch nicht die fehlende Motivation einzelner Mitarbeiter verbessern. Selbstorganisation ist nicht in allen Teamkonstellationen und unter allen Umgebungsvariablen gleichmäßig einsetzbar. Im Zuge des steigenden Projektdrucks zum Semesterende zeigte sich der zunehmende Wunsch und Bedarf vieler Teammitglieder nach einer stärkeren Taskdelegation mit klareren zeitlichen Rahmen.

 
Zusammenfassend führten uns die Erfolge und Misserfolge der Projektarbeit zu zahlreichen neuen Erkenntnissen. Die Reflexion unserer Teamarbeit zeigt Aspekte, die uns, unseres Erachtens, besonders gut gelungen sind. Jedoch mussten auch diese Erfolge, z.T. hart, gemeinsam erarbeitet werden. Sie resultierten entweder aus unzufriedenstellenden Situationen, die das Team verändern wollte und musste, um effizienter, zielgerichteter, optimierter, strukturierter, also professioneller zu arbeiten. Andererseits waren unsere hier gespiegelten Erfolge die Ergebnisse der Festlegung von Regeln und Strukturen sowie sozialer Kompetenzen. Der beim Projekt entstandene Teamgeist und die Interaktion der Mitglieder auf Augenhöhe trugen maßgeblich zu dem erfolgreichen Projektabschluss bei. Aus den in dieser Reflexion angeführten Misserfolgen zogen wir Schlussfolgerungen und leiteten Handlungsweisen für künftige Projektarbeiten ab. Einen besonderen Stellenwert nimmt hierbei die Erkenntnis ein, dass ein frühzeitiges, offenen Ansprechen von teaminternen und projektbetreffenden Problemen für eine erfolgreiche Teamarbeit essentiell ist. In einem gemeinsamen Projekt müssen Persönlichkeiten mit verschiedenen Charakteren und Fähigkeiten, unterschiedlicher Motivation und Arbeitseinstellung vereint werden. Dafür sind von Anfang an klare Regeln und Transparenz unabdingbar. Das erfolgreiche Realisieren eines Projekts besteht vorrangig in der bestmöglichen partizipativen Zusammenarbeit.