= Reflexion Software Engineering 2 – Team 3A (Habitree)
:author: Team 3A – Habitree
:revnumber: 1.0
:revdate: {docdate}
:toc: left
:sectnums:



Gruppenreflexion Software Engineering 2 - Team 3A habitree 

Im Rahmen des Modules Software Engineering 2 reflektiert Team 3A den Verlauf der gemeinsamen Projektarbeit an der Habit-Tracking App „Habitree“. Der Fokus dieser Reflexion liegt hierbei bewusst auf der Zusammenarbeit im Team, der Organisation des Projektes sowie der Anwendung agiler Vorgehensweisen und Praktiken entlang des Softwareentwicklungsprozesses. Aufbauend auf unseren teaminternen Erfahrungen, Learnings und Expertisen aus dem Modul Software Engineering 1, wurden Arbeitsweisen, Rollenverständnis und eingesetzte Werkzeuge kritisch hinterfragt, angepasst und optimiert. Die folgenden Ausführungen basieren auf Retrospektiven, Sprint Reviews und weiterer Kommunikation innerhalb des Teams. Die Reflexion zeigt nachvollziehbar einerseits zentrale Probleme verbunden mit daraus abgeleiteten Erkenntnissen, andererseits große Erfolge mit deren jeweiligen Erfolgsfaktoren. 

 
Erfolg 1: Das Projektmanagement 

Im Projektverlauf konnten mehrere Maßnahmen identifiziert werden, die sich messbar positiv auf den Teamerfolg ausgewirkt haben. Die Reduzierung von vielen verschiedenen Projektmanagementwerkzeugen auf ein wesentliches, GitHub, bewirkte eine Professionalisierung, Standardisierung und vor allem Vereinfachung des Projektmanagements. Aufgrund einer für unseren Anspruch unzureichenden Note in Software Engineering 1 entschied sich der Scrum Master während der vorlesungsfreien Zeit, das Projektmanagement anzupassen, um dessen Leistung zu steigern. Dies führte jedoch zu einem überladenen Tool-Mix. Eine im Vorfeld von Meetings erstellte, in der Cloud befindliche PowerPoint in der Cloud sollte einen Überblick über die aktuellen Themen, nächsten Schritte, Probleme und Verantwortlichkeiten geben. Außerdem wurde das GitHub Board genutzt, um aktuelle Tasks den entsprechenden Mitgliedern zuzuweisen. Hinzukommend nutzte das Team auch teilweise das Miro Board und die Discord App sowie WhatsApp für seine Meetings und asynchrone Kommunikation. Der grundlegend gute Gedanke, neue Technologien und Werkzeuge zu nutzen, um die Zusammenarbeit zu verbessern, verursachte jedoch eine Überfrachtung und Verkomplizierung der Abläufe im Projektmanagement. Daraus ergaben sich eine immense Mehrarbeit mit dem entsprechend zusätzlichen Zeitaufwand, weil verschiedene Werkzeuge zum Projektmanagement genutzt, gepflegt und geupdatet werden mussten. Daraus resultierten Inkonsistenzen zwischen den einzelnen Tools. Außerdem wurden Daten redundant mehrmals niedergeschrieben. Es herrschte Unklarheit unter den Akteuren, welches Tool gerade die aktuellste Version beinhaltete. Zudem hatten wir in Software Engineering 1 nicht konsistent unser GitHub Board und die darin enthaltenen Daten gepflegt, sodass es auch innerhalb GitHub viele verschiedene und redundante Views, Labels und Task Formate gab. Vorherige Ansprachen zur Festlegung einheitlicher Strukturen und Vorgehensweisen fehlten. Diese Inkonsistenz und unklaren Strukturen führten zu Planlosigkeit hinsichtlich der Abläufe und Umsetzung des Projekts was Ineffizienz, Missverständnisse und Frustration innerhalb des Teams befeuerte. Beispielsweise führten diese Arbeitsweisen dazu, dass entsprechende Tasks im Meeting per PowerPoint vergeben wurden, ohne sie auf GitHub einzustellen und den Teammitgliedern sichtbar zuzuordnen. Dadurch wurden Aufgaben nicht gefunden und damit nicht erledigt. Zu viele (redundante) Labels mündeten in zu viele Views und erschwerten die Übersichtlichkeit. Um neue, präzisere und effizientere Strukturen zu erschaffen, beschlossen wir in einem längeren Meeting, bestehende Inkonsistenzen zu beseitigen. Unsere Maßnahmen betrafen einerseits die Reduzierung überschüssiger Views und Labels im GitHub, die Einführung neuer und klarer Sichten in unserem Project Board, die Vereinheitlichung der User Story - und Task Formate sowie die Ergänzung von Akzeptanzkriterien zu den entsprechenden Tasks. Das Ziel bestand in der Schaffung klarer Strukturen, um verständliche Arbeitsabläufe und ein schnelleres und übersichtliches Arbeiten, somit ein zielführendes Arbeiten im Team zu ermöglichen und besser nach gängigen Scrum Methoden zu agieren. So wurden wichtige Sichten wie Sprint- Backlog -> Tasks from User Stories oder ein Product Backlog -> User Stories angepasst und vereinfacht.  Die verbesserte Übersichtlichkeit und Verständlichkeit schaffte ein einheitliches Methodenverständnis unter allen Akteuren des Teams. Überflüssige Tools bzw. Medien wie PowerPoint wurden abgeschafft. Neben der nun minimierten Doppelpflege, Medienbrüchen und Verwirrung innerhalb des Teams, führte diese Maßnahme auch zu einer transparenteren Arbeitsteilung und einer klaren Zuordnung von Tasks. Anders als in einer PowerPoint-Tabelle, erfolgte auf GitHub eine explizite Benachrichtigung der einzelnen Mitglieder über Aufgaben. Dies verhinderte, dass Aufgaben übersehen oder vergessen wurden. Die alleinige Nutzung von GitHub zur Zuordnung von Aufgaben schuf einen zentralen Ort, an dem alle Teammitglieder ihre Aufgaben einsehen und bearbeiten konnten. Durch die Einführung klarer und feingranularer Labels und die gleichzeitige Minimierung der Labelanzahl beeinflusste die Kenntnis über anstehende Tasks und deren zeitnahes Abarbeiten maßgeblich positiv. Hierfür nahmen wir eine Untergliederung in Story-, Documentation- und Implementation-Task vor. Während Story Tasks abgeleitete Programmierungs- bzw. Implementations-Aufgaben im Code zur Erfüllung von den User Stories darstellten, beinhalteten Documentation -Tasks konkrete Fakten, die in die einzelnen Dokumente eingebunden werden mussten. Implementation-Task dienten zur Bearbeitung allgemeiner technischer Probleme und Aufgabenstellungen, die nicht direkt aus einer User Story abgeleitet wurden bzw. werden konnten. Wenn ein Mitglied nun einen Task assigned wurde, wusste es somit intuitiv, auf welche Problemdimension der jeweilige Task sich referenziert.  

  
Erfolg 2: Die Scrum-Arbeitsweisen 

Neben der Optimierung des Projektmanagements wurden auch unsere Scrum-Arbeitsweisen strukturiert und weiterentwickelt. So veränderten wir unter anderem bestehende Meeting-Formate und verbesserten unsere wöchentlichen Meetings, in denen nun eine effiziente Statusbesprechung und Planung der nächsten Schritte und Meilensteine, eine Abwägung von Risiken und eine Problemevaluierung erfolgte. Zudem führten wir auch zu Beginn eines jeden Sprints ein Sprint Planning-Meeting ein, in welchem der Product Owner im Vorfeld priorisierte User Stories einbrachte und mit dem Entwicklerteam diese hinsichtlich ihrer Komplexität, Machbarkeit und ihres Aufwandes einschätzte. Am Meeting-Ende fand jeweils eine teaminterne Retrospektive statt, in der jedes Mitglied seine Zufriedenheit quantifizieren und begründen sollte. Ergänzend wurde ein Set an Key Performance Indicators mit einem Happiness Index, Kapazitätsübersicht sowie einer Task- Fortschrittsrate eingefügt. Die KPIs dienten primär nicht als Kontrollinstrument, sondern sollten vielmehr dem Scrum Master zur besseren Einschätzung des Teams bezüglich Belastung, Stimmung und Arbeitsfortschritte ermöglichen. Die Kapazitätsübersicht half uns hierbei, grobe Tendenzen hinsichtlich verfügbarer Arbeitszeiten sichtbar zu gestalten, auch wenn studentische Einsatzmöglichkeiten naturgemäß schwanken und nur schwer planbar sind.   
Zusammenfassend führten eine klare und effizientere Meeting-Struktur, die sich an gängigen Scrum Best Practices orientierte, dazu, dass die Kommunikation und Planung erleichtert wurden. Strukturierte Meetings führten dazu, dass wesentlich weniger Zeit für nicht projektspezifische Diskussionen verwendet wurde als in SE 1. Auch wenn die Metriken nicht alle Planungsprobleme lösen konnten, unterstützten Sie uns dabei, Entwicklungen früher wahrzunehmen, zu quantifizieren und proaktiv auf Probleme reagieren zu können. 


Erfolg 3: Der Zusammenhalt innerhalb des Teams 

Ein weiterer positiver Aspekt, der maßgeblich zum Erfolg der Projektarbeit beitrug, bestand im grundsätzlich starken Zusammenhalt des Teams mit der klaren Rollenverteilung. Prinzipiell bildete sich innerhalb der Module SE 1 und SE 2 ein Team, das sich, bis auf wenige Ausnahmen, gegenseitige Wertschätzung entgegenbrachte, nach klaren Regeln agierte, gemeinsame Visionen formulierte und erfolgversprechend zusammenarbeitete. Zudem wurde zu Beginn des Software Engineering 2 Modules auch erfolgreich ein neues, zugelostes, Teammitglied in die bestehenden Strukturen integriert. Unsere Rollen warten klar verteilt und wurden in SE 2 geschärft. Unser Product Owner verfügte über das Domänenwissen hinsichtlich Habits und hatte einen konkreten Überblick über Visionen, User Stories und Features. Er priorisierte User Stories, welche anschließend in dem Sprint Planning Meeting vor allem mit dem Entwicklerteam hinsichtlich Komplexität und Aufwand gewichtet und bewertet wurden. Der zuverlässige Scrum Master war für die Organisation und Abwicklung aller Meetings zuständig, sofern es sich nicht um spezialisierte Dev.-Team Meetings handelte. Zudem stellte er die unterstützende und ausgleichende Instanz bei Konflikten und Problemen dar. Seine weiteren Aufgaben bestanden im groben Projektcontrolling, auch hinsichtlich eingesetzter Techniken. Er sicherte die Übereinstimmung der Ist-Techniken mit den aus der Vorlesung und dem Praktikum vermittelten Soll- Techniken. Zudem unterstützte er den Product Owner. Das Dev.-Team war für die konkrete Implementierung und Validierung von Habitree zuständig. Innerhalb dieses Teams ergaben sich spezifische Zuständigkeitsbereiche ergaben, zum Beispiel die Verantwortlichkeiten für das Backend, Frontend und das Testen. Dabei zeigte sich das Problem der Wissensinseln. Dank der wöchentlichen Meetings und einem Austausch innerhalb des gesamten Entwicklerteams konnten diese erfolgreich behoben werden. Die jetzige Beständigkeit unserer Teamstruktur baute auf verschiedenen Problemen auf, die in der Vergangenheit erfolgreich gemanagt wurden. Unter anderem bewältigten wir den Austritt eines Teammitgliedes noch in SE 1, überzeugten ein nicht konstant arbeitendes Teammitglied von der Notwendigkeit kontinuierlichen Arbeitens und behoben Kommunikationsprobleme durch verschiedene synchrone und asynchrone Kommunikationswege. Diese überwundenen Hürden führten dazu, dass jeder seine Rolle und seinen Beitrag für das Team kannte und erbrachte. Fast alle unserer Meetings zeichneten sich durch eine hohe Teilnehmerzahl und ein stets wertschätzendes Klima mit relativ flachen Hierarchien aus.  

 
Misserfolg 1: Sprint Managment 

Unsere Teamarbeit bestand jedoch nicht nur aus erfolgreichen Erlebnissen, auch Misserfolge prägten die Arbeit. Einen Misserfolg verzeichnete das Sprint Management bedingt durch Planungsprobleme aufgrund schwankender zeitlicher Kapazitäten der einzelnen Mitglieder.  Unser Sprint Management stand im gesamten Modul vor wiederkehrenden Herausforderungen, die primär aus der studentischen Situation resultierten. So wurde unser Projekt nicht in Vollzeit durchgeführt, sondern parallel zu verschiedenen anderen Modulen, Deadlines, Praktika und anderen Projekten. Somit variierten die zeitlichen Verfügbarkeiten der einzelnen Mitarbeiter zwischen und innerhalb der einzelnen Wochen erheblich. Zu Beginn jedes Sprints priorisierten wir User Stories im Sprint Planning-Meeting, zerlegten diese in konkrete Aufgaben und nahmen sie in das Sprint Backlog auf. Zudem erfragte der Scrum Master wöchentlich, auch im Zuge der KPI-Auswertung, die Einsatzfähigkeit der Mitglieder in Stunden (z.B.: innerhalb des Kapazitätsboards in GitHub). Trotz dieser Workflows zeigten sich jedoch Probleme innerhalb der eigentlichen Umsetzung. So konnten wir in einigen Iterationen deutlich mehr leisten als geplant, sodass der Sprint nach zwei Wochen schon vollständig abgeschlossen war. Andere Sprints verliefen langsamer, als erwartet, sodass nicht alle geplanten Tasks abgearbeitet wurden. Dies führte zu einer Divergenz zwischen dem theoretischen Scrum Timeboxing und der Anwendung der Scrum Praktiken im studentischen Alltag. Daher änderten wir das Sprint- Framework leicht ab, um auf die sich schnell ändernde studentische Umwelt angepasst zu sein. Wurde ein Sprint mit all seinen Aufgaben deutlich vorzeitig abgeschlossen (als Zeitpunkt setzten wir 10 Tage vor dem eigentlichen Ende an), führten wir ein Refill-Meeting ein, um neue Stories aus dem Product Backlog aufzunehmen.  Wie im eigentlichen Sprint Planning-Meeting wurden die entsprechenden Product Backlog Items erst vom Product Owner priorisiert, dann innerhalb des Teams hinsichtlich Komplexität und Aufwand gewichtet. Anschließend wurden konkrete Tasks abgeleitet. Das Ziel bestand darin, unnötige Leerlaufzeit zu vermeiden und den Geschäftswert kontinuierlich zu steigern. Nicht bis zum Sprint-Ende abgeschlossene Aufgaben wurden aus dem alten Sprint entfernt, erneut refined und für den nächsten Sprint eingeplant. Die bewusste Abweichung von den in der Vorlesung geschilderten Scrum Prinzipien barg auch einige Nachteile. So verschwommen teilweise die Sprint-Grenzen, was die Transparenz, vor allem auch gegenüber Stakeholdern in Sprint Reviews negativ beeinflusste. Auch die Planbarkeit und strategische Steuerung des Projektes wurde komplexer. Wir lernten, dass Sprints im universitären Umfeld anders funktionieren als in Vollzeit- Produktteams. Während in Scrum formell davon ausgegangen wird, dass Teams eine annährend konstante Velocity besitzen, sind studentische Teams eher volatil und somit tendenziell schlechter planbar. In der beruflichen Praxis ist es selten der Fall, dass z.B.: Mitarbeiter nur für 3 bis 10 Stunden pro Woche für ein Projekt eingesetzt sind. Unser adaptives Vorgehen wich zwar von einigen gängigen Scrum Best Pratices ab (u.a. dass Sprints nicht mit weiteren PBIs nachgefüllt werden sollten), ergab jedoch aus Projektsicht einen sinnvollen Kompromiss. In zukünftigen Projekten würden wir Sprints bewusst kürzer halten. So setzten wir für unseren letzten Sprint nur eine Dauer von 14 Tagen an. Wir bemerkten, dass kapazitive Schwankungen auf kürzere Zeit tendenziell geringer ausfallen. Zudem würden wir dieses Thema auch schon frühzeitig in unser Risikoboard aufnehmen. Entstandene Pufferzeiten in Sprints würden wir vor allem mit der Beseitigung von Bugs, der Erledigung von Dokumentationsaufgaben und der Verbesserung unserer Architektur und unseres Codes verbringen.  

 

Misserfolg 2: Die Inselkompetenzen 
Ein weiterer Misserfolg bestand in der Entstehung von Inselkompetenzen und eines fehlenden horizontalen Wissenstransfers. Im Verlauf des Projektes fand eine zunehmende Spezialisierung des Teams in klar voneinander abgegrenzte Domänen, gemäß der Rollen und Verantwortlichkeiten, statt. Gerade bei kleineren Teamgrößen empfanden wir diesen Aspekt sinnhaft, allerdings führte er zur Entwicklung von Spezialkompetenzen, Wissensinseln. Jedes Teammitglied ging in seiner Aufgabe auf und perfektionierte sich. Der Scrum Master war primär für die Meeting Planung, Prozessüberwachung und die Sicherstellung der agilen Arbeitsweise verantwortlich, der Product Owner kümmerte sich um das Stakeholdermanagement sowie die Priorisierung von User Stories. Das Entwicklerteam untergliederte sich in weitere Subdomänen. Es gab jeweils Verantwortliche für das Frontend, Backend und die Testgestaltung. Diese Spezialisierung bewirkte, dass die Teammitglieder über die Sprints hinweg sich immer tiefer in ihre jeweiligen Subdomänen einarbeiteten. Ein ganzheitlicher horizontaler Wissenstransfer fand aber nicht statt. Das führte zu Problemen. Im Krankheitsfall eines Teammitglieds konnten Tasks entweder gar nicht oder nur unzureichend von anderen Teammitglieder umgesetzt werden. Der zweiwöchige krankheitsbedingte Ausfall unseres Datenbankverantwortlichen verursachte, dass Features nicht vollständig implementiert werden konnten. Der Grund dafür lag darin, dass andere Teammitglieder die Implementierung in die Datenbank aufgrund unzureichender Kenntnisse nur mit unzufriedenstellender Qualität umsetzen konnten. Das Team war dadurch nur eingeschränkt in der Lage, flexibel auf zeitkritische Risiken zu reagieren, welche aufgrund des Ausfalls einzelner Mitglieder hervorgerufen wurden. Die Einarbeitung in fremde Themengebiete erforderte einen hohen Einarbeitungsaufwand, da die Interaktion zwischen den einzelnen Teammitgliedern nur an Schnittstellen zwischen Verantwortlichkeitsbereichen stattfand.  
Um dieses Problem zu vermeiden, könnte man künftig Pair Programming einführen, um Wissen direkt zwischen den Rollen auszutauschen. Zudem muss ein noch stärkerer Fokus auf eine saubere, konsistente und prägnante Dokumentation gelegt werden, sodass man sich Rollenwissen direkt anlesen kann. Des Weiteren könnte man Backup-Rollen definieren, sodass jeder Zuständigkeitsbereich von mindestens zwei Gruppenmitglieder prinzipiell erledigt werden kann. Wir erkannten, dass technische Spezialisierung zwar effizient erscheint, jedoch langfristig zu strukturellen Risiken führen kann. Um eine nachhaltige Arbeitsweise im Team hervorzubringen, muss Wissen unter den Mitgliedern aktiv geteilt und ausgetauscht werden. Software Engineering ist Teamarbeit und bedarf neben technischen auch eine Vielzahl sozialer Kompetenzen. 

 
Misserfolg 3: Der Zusammenarbeit innerhalb des Teams 

Ein weiterer Misserfolg zeigte sich in der selbstorganisierten Zusammenarbeit. Schwankende individuelle Motivation und Einsatzbereitschaft einzelner Mitglieder beeinflusste die effektive, erfolgreiche Zusammenarbeit, trotz einer grundsätzlich stabilen Teamstruktur, negativ. Bereits gegen Ende von Software Engineering 1 zeigte sich deutlich, dass einzelne Teammitglieder unterschiedlich stark zur Gruppenleistung beitrugen. Diese Entwicklung setzte sich in Software Engineering 2 fort und wurde mit wachsendem Projektumfang noch stärker ersichtlich. Obwohl wir die allgemeine Teamdynamik positiv empfanden, nahm ein Mitglied nahm, wenn überhaupt, nur passiv an den Meetings teil und erledigte seine Tasks nur in geringer Qualität. So mussten Aufgaben wie Wire Frames, Sequenzdiagramme oder auch Teile des Benutzerhandbuchs von anderen Mitgliedern entweder verbessert oder gänzlich übernommen werden, um den teaminternen Qualitätsanforderungen zu entsprechen. Verstärkt wurde diese Situation dadurch, dass unsere Teamkultur auf flachen Hierarchien, Freiwilligkeit sowie Vertrauen basierte. Derartige Strukturen sind wirkungsvoll, solange Motivation, Arbeitsweise und Wissen aller Mitarbeiter vergleichbar sind. Divergiert der Reifegrad der Mitarbeiter jedoch signifikant, stößt ein demokratischer Führungsstil an seine Grenzen. Um den Projektfortschritt dennoch sicherzustellen, passten wir unseren Führungsstil situativ an. Dafür orientierten wir uns am Reifegradmodell von Hersey und Blanchard. Uns war bewusst Stilbruch mit gängigen Scrum Methoden. Wir führten für Teammitglieder mit geringerer Motivation verbindliche Prozesse mit klar definierten Aufgaben und Deadlines ein. Dies zeigte kurzfristig Verbesserung, konnte aber dennoch nicht die fehlende Motivation einzelner Mitarbeiter verbessern. Selbstorganisation ist nicht in allen Teamkonstellationen und unter allen Umgebungsvariablen gleichmäßig einsetzbar. Im Zuge des steigenden Projektdrucks zum Semesterende zeigte sich der zunehmende Wunsch und Bedarf vieler Teammitglieder nach einer stärkeren Taskdelegation mit klareren zeitlichen Rahmen.  

 
Zusammenfassend führten uns die Erfolge und Misserfolge der Projektarbeit zu zahlreichen neuen Erkenntnissen. Die Reflexion unserer Teamarbeit zeigt Aspekte, die uns, unseres Erachtens, besonders gut gelungen sind. Jedoch mussten auch diese Erfolge, z.T. hart, gemeinsam erarbeitet werden. Sie resultierten entweder aus unzufriedenstellenden Situationen, die das Team verändern wollte und musste, um effizienter, zielgerichteter, optimierter, strukturierter, also professioneller zu arbeiten. Andererseits waren unsere hier gespiegelten Erfolge die Ergebnisse der Festlegung von Regeln und Strukturen sowie sozialer Kompetenzen. Der beim Projekt entstandene Teamgeist und die Interaktion der Mitglieder auf Augenhöhe trugen maßgeblich zu dem erfolgreichen Projektabschluss bei. Aus den in dieser Reflexion angeführten Misserfolgen zogen wir Schlussfolgerungen und leiteten Handlungsweisen für künftige Projektarbeiten ab. Einen besonderen Stellenwert nimmt hierbei die Erkenntnis ein, dass ein frühzeitiges, offenen Ansprechen von teaminternen und projektbetreffenden Problemen für eine erfolgreiche Teamarbeit essenziell ist. In einem gemeinsamen Projekt müssen Persönlichkeiten mit verschiedenen Charakteren und Fähigkeiten, unterschiedlicher Motivation und Arbeitseinstellung vereint werden. Dafür sind von Anfang an klare Regeln und Transparenz unabdingbar. Das erfolgreiche Realisieren eines Projekts besteht vorrangig in der bestmöglichen partizipativen Zusammenarbeit. 
