@startuml
title Domänenmodell – Habit Tracker (integriert mit HabitStack)

skinparam classAttributeIconSize 0

'=======================
' Hauptklassen (Kernmodell)
'=======================

class User {
  - email
  - username
  - createdAt
  - Recovery Mode ()
}

class Habit {
  - name
  - description
  - frequency
  - createdAt
  - currentStreak ()
  - maxStreak ()
}

class HabitEntry {
  - date
  - status
  - note
}
class Tagebucheintrag {
  - date: Date
  - content: Text
  - mood: String
  - weather: String
}

class Tagebuch {
  - title
  - createdAt
}
class seasonal_challenges {
  - title
  - description
  - season
  - isActive
}
class Statistik {
  - totalHabits
  - completedEntries
  - successRate
  - averageMood
}

class Dashboard {
  - dailyOverview
  - weeklySummary
  - habitHighlights
}
class Grafen {
  - type
  - dataRange
  - title
}
class Wissensbereich {
  - topic
  - content
  - mediaType
}
class HabitStack {
  - name
  - ammount of Habits
  - order
}


'=======================
' Beziehungen
'=======================
Wissensbereich - User : wird genutzt von >
Tagebuch "1" *- "0..*" Tagebucheintrag : enthält >


User "1" *-- "0..*" Habit : besitzt >
User "1" -- "0..*"HabitStack : erstellt Stack >
User "0..*"-- "0..*"seasonal_challenges : nutzt >
User "1" *- "0..*" Tagebuch : führt >

HabitStack "1" o-- "1..*" Habit : enthält >
seasonal_challenges -- "1..*" Habit : beinhaltet >


Habit "1" *-- "0..*" HabitEntry : enthält >
Habit *- Statistik : bekommt Daten von <


Statistik *-- Dashboard : zeigt Daten >
Statistik *- Grafen : wird interpretiert als >




@enduml
