@startuml
title Domänenmodell – Habit Tracker (integriert mit HabitStack)

skinparam classAttributeIconSize 0

'=======================
' Hauptklassen (Kernmodell)
'=======================

class User {
  - email
  - username
  - createdAt
  - Anzahl Streaks (Eigen)
  - Anzahl Streaks (Freunde)
  - Anzahl Rückgriffe
  - Recovery Mode (true/false)
}

class Habit {
  - name
  - description
  - frequency
  - createdAt
  - hasReminder
  - currentStreak
  - maxStreak
}

class HabitEntry {
  - date
  - status
  - note
}


class HabitStack
class Tagebucheintrag



class seasonal_challenges
class Tagebuch


class Statistik
class Dashboard
class Wissenschaftsbereich

'=======================
' Beziehungen
'=======================

User "1" -- "0..*" Habit : besitzt >
Habit "1" -- "0..*" HabitEntry : hat >

HabitStack -- "1..*" Habit : besteht aus >

Habit -- Statistik

User -- HabitStack : erstellt Stack >



User -- Tagebuch
User -- seasonal_challenges
seasonal_challenges -- Habit : besteht aus >

Wissenschaftsbereich -- User : ruft ab >

Statistik -- Dashboard : zeigt an >
Statistik -- Grafen : wird interpretiert als >

@enduml
